@startuml

title __FEATURE's Class Diagram__\n

  namespace com.grandtech.echart {
    namespace feature {
      class com.grandtech.echart.feature.DataView {
          + DataView()
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace feature {
      class com.grandtech.echart.feature.DataZoom {
          - yAxisIndex : Object
          + DataZoom()
          + yAxisIndex()
          + yAxisIndex()
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace feature {
      class com.grandtech.echart.feature.Feature {
          {static} + dataView : DataView
          {static} + dataZoom : DataZoom
          {static} + magicType : MagicType
          {static} + mark : Mark
          {static} + restore : Restore
          {static} + saveAsImage : SaveAsImage
          - icon : String
          - lang : Object
          - readOnly : Boolean
          {static} - serialVersionUID : long
          - show : Boolean
          - title : Object
          - type : Object
          + getIcon()
          + getLang()
          + getLineStyle()
          + getReadOnly()
          + getShow()
          + getTextStyle()
          + getTitle()
          + getType()
          + icon()
          + icon()
          + lang()
          + lang()
          + lineStyle()
          + lineStyle()
          + readOnly()
          + readOnly()
          + setIcon()
          + setLang()
          + setLineStyle()
          + setReadOnly()
          + setShow()
          + setTextStyle()
          + setTitle()
          + setType()
          + show()
          + show()
          + textStyle()
          + textStyle()
          + title()
          + title()
          + type()
          + type()
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace feature {
      class com.grandtech.echart.feature.MagicType {
          + MagicType()
          + getOption()
          + option()
          + option()
          + setOption()
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace feature {
      class com.grandtech.echart.feature.MagicType.Option {
          + funnel()
          + funnel()
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace feature {
      class com.grandtech.echart.feature.Mark {
          + Mark()
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace feature {
      class com.grandtech.echart.feature.Restore {
          + Restore()
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace feature {
      class com.grandtech.echart.feature.SaveAsImage {
          + SaveAsImage()
      }
    }
  }
  

  com.grandtech.echart.feature.DataView -up-|> com.grandtech.echart.feature.Feature
  com.grandtech.echart.feature.DataZoom -up-|> com.grandtech.echart.feature.Feature
  com.grandtech.echart.feature.Feature .up.|> java.io.Serializable
  com.grandtech.echart.feature.Feature o-- com.grandtech.echart.style.LineStyle : lineStyle
  com.grandtech.echart.feature.Feature o-- com.grandtech.echart.style.TextStyle : textStyle
  com.grandtech.echart.feature.MagicType -up-|> com.grandtech.echart.feature.Feature
  com.grandtech.echart.feature.MagicType o-- com.grandtech.echart.feature.MagicType.Option : option
  com.grandtech.echart.feature.MagicType +-down- com.grandtech.echart.feature.MagicType.Option
  com.grandtech.echart.feature.MagicType.Option o-- com.grandtech.echart.series.Funnel : funnel
  com.grandtech.echart.feature.Mark -up-|> com.grandtech.echart.feature.Feature
  com.grandtech.echart.feature.Restore -up-|> com.grandtech.echart.feature.Feature
  com.grandtech.echart.feature.SaveAsImage -up-|> com.grandtech.echart.feature.Feature


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
