@startuml

title __LISTENER's Class Diagram__\n

  namespace com.gykj.arcgistool {
    namespace listener {
      interface com.gykj.arcgistool.listener.IDrawGraphListener {
          {abstract} + drawEnd()
          {abstract} + drawStart()
      }
    }
  }
  

  namespace com.gykj.arcgistool {
    namespace listener {
      interface com.gykj.arcgistool.listener.IDrawListener {
          {abstract} + onDrawEnd()
          {abstract} + onDrawStart()
      }
    }
  }
  

  namespace com.gykj.arcgistool {
    namespace listener {
      interface com.gykj.arcgistool.listener.IMeasureClickListener {
          {abstract} + areaClick()
          {abstract} + clearClick()
          {abstract} + endClick()
          {abstract} + lengthClick()
          {abstract} + nextClick()
          {abstract} + prevClick()
      }
    }
  }
  

  namespace com.gykj.arcgistool {
    namespace listener {
      interface com.gykj.arcgistool.listener.IOnTouchListener {
          {abstract} + onDoubleTap()
          {abstract} + onDoubleTapEvent()
          {abstract} + onDoubleTouchDrag()
          {abstract} + onDown()
          {abstract} + onFling()
          {abstract} + onLongPress()
          {abstract} + onMultiPointerTap()
          {abstract} + onRotate()
          {abstract} + onScale()
          {abstract} + onScaleBegin()
          {abstract} + onScaleEnd()
          {abstract} + onScroll()
          {abstract} + onShowPress()
          {abstract} + onSingleTapConfirmed()
          {abstract} + onSingleTapUp()
          {abstract} + onTouch()
          {abstract} + onUp()
      }
    }
  }
  

  namespace com.gykj.arcgistool {
    namespace listener {
      interface com.gykj.arcgistool.listener.IZoomClickListener {
          {abstract} + mapMainClick()
          {abstract} + mapRotateClick()
          {abstract} + zoomInClick()
          {abstract} + zoomOutClick()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
