@startuml

title __CUSTOM's Class Diagram__\n

  namespace com.grandtech.mapframe.core {
    namespace snapshot {
      namespace custom {
        abstract class com.grandtech.mapframe.core.snapshot.custom.DbCommand {
            {static} + BLOCKINGQUEUE_LENGTH : int
            {static} + KEEPALIVETIME : int
            {static} + PROCESSORS : int
            {static} - sHandler : Handler
            {static} - threadFactory : ThreadFactory
            {static} - threadPool : ThreadPoolExecutor
            + execute()
            {abstract} # doInBackground()
            # onPostExecute()
            - postResult()
        }
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace snapshot {
      namespace custom {
        class com.grandtech.mapframe.core.snapshot.custom.MapScreenshotTool {
            - cutBuffer : int
            - stop : boolean
            + createMapScreenshots()
            + createMapScreenshotsAsync()
            + reStartCreateMapScreenshotsTask()
            + searchZoomTiles()
            + stopCreateMapScreenshotsTask()
            - cutImageWithPolygonCenter()
            - drawPolygon()
            - drawPolygonMark()
            - drawRectAndSzzb()
            - drawTileImageAsync()
            - drawWaters()
            - getImage()
            - toRequestImgTile()
        }
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace snapshot {
      namespace custom {
        interface com.grandtech.mapframe.core.snapshot.custom.MapScreenshotTool.ICallBack {
            {abstract} + complete()
            {abstract} + onError()
        }
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace snapshot {
      namespace custom {
        class com.grandtech.mapframe.core.snapshot.custom.ScreenshotsFeatureStye {
            {static} + CELL : String
            {static} + FILL : String
            {static} + NULL : String
            - color : int
            - drawPolygonMark : boolean
            - feature : Feature
            - fillColor : int
            - fillType : String
            - strokeSize : float
            + getColor()
            + getFeature()
            + getFillColor()
            + getFillType()
            + getStrokeSize()
            + isDrawPolygonMark()
            + setColor()
            + setDrawPolygonMark()
            + setFeature()
            + setFillColor()
            + setFillType()
            + setStrokeSize()
        }
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace snapshot {
      namespace custom {
        class com.grandtech.mapframe.core.snapshot.custom.ScreenshotsSetting {
            - drawRect : boolean
            - imageQuality : float
            - imageScale : float
            - imageUrl : String
            - otherImageUrls : List<String>
            - screenshotsFeatureStyes : List<ScreenshotsFeatureStye>
            - tileDensity : double
            - waters : List<String>
            - zoom : int
            + addScreenshotsFeatureStye()
            {static} + getFeatureCollections()
            + getImageQuality()
            + getImageScale()
            + getImageUrl()
            + getOtherImageUrls()
            + getScreenshotsFeatureStyes()
            + getTileDensity()
            + getWaters()
            + getZoom()
            + isDrawRect()
            + setDrawRect()
            + setImageQuality()
            + setImageScale()
            + setImageUrl()
            + setOtherImageUrls()
            + setScreenshotsFeatureStyes()
            + setTileDensity()
            + setWaters()
            + setZoom()
        }
      }
    }
  }
  

  com.grandtech.mapframe.core.snapshot.custom.MapScreenshotTool .up.|> com.grandtech.mapframe.core.rules.Rules
  com.grandtech.mapframe.core.snapshot.custom.MapScreenshotTool +-down- com.grandtech.mapframe.core.snapshot.custom.MapScreenshotTool.ICallBack
  com.grandtech.mapframe.core.snapshot.custom.ScreenshotsFeatureStye .up.|> com.grandtech.mapframe.core.rules.Rules
  com.grandtech.mapframe.core.snapshot.custom.ScreenshotsFeatureStye .up.|> java.io.Serializable
  com.grandtech.mapframe.core.snapshot.custom.ScreenshotsSetting .up.|> com.grandtech.mapframe.core.rules.Rules
  com.grandtech.mapframe.core.snapshot.custom.ScreenshotsSetting .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
