@startuml

title __UTIL's Class Diagram__\n

  namespace com.gykj.selectlinearlayout {
    namespace util {
      class com.gykj.selectlinearlayout.util.ConvertUtils {
          {static} + GB : long
          {static} + KB : long
          {static} + MB : long
          {static} + toArray()
          {static} + toBinaryString()
          {static} + toBinaryString()
          {static} + toBitmap()
          {static} + toBitmap()
          {static} + toBitmap()
          {static} + toBitmap()
          {static} + toByteArray()
          {static} + toByteArray()
          {static} + toByteArray()
          {static} + toByteArray()
          {static} + toByteArray()
          {static} + toColorStateList()
          {static} + toColorStateList()
          {static} + toColorString()
          {static} + toColorString()
          {static} + toDarkenColor()
          {static} + toDarkenColor()
          {static} + toDp()
          {static} + toDrawable()
          {static} + toDrawable()
          {static} + toFileSizeString()
          {static} + toFloat()
          {static} + toGbk()
          {static} + toHexString()
          {static} + toHexString()
          {static} + toHexString()
          {static} + toInt()
          {static} + toInt()
          {static} + toList()
          {static} + toLong()
          {static} + toPath()
          {static} + toPx()
          {static} + toShort()
          {static} + toSlashString()
          {static} + toSp()
          {static} + toString()
          {static} + toString()
          {static} + toString()
          {static} + toString()
          {static} - _queryPathFromMediaStore()
      }
    }
  }
  

  namespace com.gykj.selectlinearlayout {
    namespace util {
      class com.gykj.selectlinearlayout.util.LogUtils {
          {static} - MAX_STACK_TRACE_SIZE : int
          {static} - METHOD_COUNT : int
          {static} - MIN_STACK_OFFSET : int
          {static} - debugTag : String
          {static} - isDebug : boolean
          {static} + debug()
          {static} + debug()
          {static} + debug()
          {static} + error()
          {static} + error()
          {static} + error()
          {static} + error()
          {static} + error()
          {static} + getDebugTag()
          {static} + isDebug()
          {static} + setDebugTag()
          {static} + setIsDebug()
          {static} + startMethodTracing()
          {static} + stopMethodTracing()
          {static} + toStackTraceString()
          {static} + verbose()
          {static} + verbose()
          {static} + verbose()
          {static} + warn()
          {static} + warn()
          {static} + warn()
          {static} + warn()
          {static} + warn()
          {static} - _getSimpleClassName()
          {static} - _getStackOffset()
          {static} - getTraceElement()
      }
    }
  }
  

  namespace com.gykj.selectlinearlayout {
    namespace util {
      class com.gykj.selectlinearlayout.util.ScreenUtils {
          {static} - dm : DisplayMetrics
          {static} - isFullScreen : boolean
          {static} + density()
          {static} + densityDpi()
          {static} + displayMetrics()
          {static} + heightPixels()
          {static} + isFullScreen()
          {static} + keepBright()
          {static} + toggleFullScreen()
          {static} + widthPixels()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
