@startuml

title __UTIL's Class Diagram__\n

  namespace com.baidu.ocr.ui {
    namespace util {
      class com.baidu.ocr.ui.util.DimensionUtil {
          {static} + dpToPx()
      }
    }
  }
  

  namespace com.baidu.ocr.ui {
    namespace util {
      class com.baidu.ocr.ui.util.FileUtil {
          {static} + getSaveFile()
      }
    }
  }
  

  namespace com.baidu.ocr.ui {
    namespace util {
      interface com.baidu.ocr.ui.util.IdCardType {
      }
    }
  }
  

  namespace com.baidu.ocr.ui {
    namespace util {
      class com.baidu.ocr.ui.util.ImageUtil {
          {static} - TAG : String
          {static} + calculateInSampleSize()
          {static} + exifToDegrees()
          {static} + getOrientation()
          {static} - pack()
      }
    }
  }
  

  namespace com.baidu.ocr.ui {
    namespace util {
      class com.baidu.ocr.ui.util.OcrUtils {
          {static} + IDCARD_BACK : String
          {static} + IDCARD_FRONT : String
          {static} + defultResult : String
          {static} - analyzer : MLIcrAnalyzer
          {static} + animalDetect()
          {static} + ingredient()
          {static} + plantDetect()
          {static} + recBankCard()
          {static} + recBusinessLicense()
          {static} + recIDCard()
          {static} + release()
          {static} + scanBcrResult()
          {static} + scanIDResult()
      }
    }
  }
  

  namespace com.baidu.ocr.ui {
    namespace util {
      interface com.baidu.ocr.ui.util.OcrUtils.OnAnimalDetectResultListenerAi {
          {abstract} + onAnimalDetectLicense()
          + onError()
      }
    }
  }
  

  namespace com.baidu.ocr.ui {
    namespace util {
      interface com.baidu.ocr.ui.util.OcrUtils.OnBankCardOcrResultListenerAli {
          + onError()
          {abstract} + onOcrResultBankCard()
      }
    }
  }
  

  namespace com.baidu.ocr.ui {
    namespace util {
      interface com.baidu.ocr.ui.util.OcrUtils.OnBusinessLicenseOcrResultListenerAli {
          {abstract} + OnOcrResultBusinessLicense()
          + onError()
      }
    }
  }
  

  namespace com.baidu.ocr.ui {
    namespace util {
      interface com.baidu.ocr.ui.util.OcrUtils.OnIDCardOcrResultListenerAli {
          + onError()
          {abstract} + onOcrResultIDCard()
      }
    }
  }
  

  namespace com.baidu.ocr.ui {
    namespace util {
      interface com.baidu.ocr.ui.util.OcrUtils.OnIngredientResultListenerAi {
          + onError()
          {abstract} + onIngredientLicense()
      }
    }
  }
  

  namespace com.baidu.ocr.ui {
    namespace util {
      interface com.baidu.ocr.ui.util.OcrUtils.OnPlantDetectResultListenerAi {
          + onError()
          {abstract} + onPlantDetectLicense()
      }
    }
  }
  

  com.baidu.ocr.ui.util.OcrUtils -up-|> com.baidu.net.RequestUtil
  com.baidu.ocr.ui.util.OcrUtils +-down- com.baidu.ocr.ui.util.OcrUtils.OnAnimalDetectResultListenerAi
  com.baidu.ocr.ui.util.OcrUtils +-down- com.baidu.ocr.ui.util.OcrUtils.OnBankCardOcrResultListenerAli
  com.baidu.ocr.ui.util.OcrUtils +-down- com.baidu.ocr.ui.util.OcrUtils.OnBusinessLicenseOcrResultListenerAli
  com.baidu.ocr.ui.util.OcrUtils +-down- com.baidu.ocr.ui.util.OcrUtils.OnIDCardOcrResultListenerAli
  com.baidu.ocr.ui.util.OcrUtils +-down- com.baidu.ocr.ui.util.OcrUtils.OnIngredientResultListenerAi
  com.baidu.ocr.ui.util.OcrUtils +-down- com.baidu.ocr.ui.util.OcrUtils.OnPlantDetectResultListenerAi


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
