@startuml

title __ADAPTER's Class Diagram__\n

  namespace com.gykj.cameramodule {
    namespace adapter {
      class com.gykj.cameramodule.adapter.ImgFolderAdapter {
          + ImgFolderAdapter()
          + isPosItemVisible()
          + onCreateViewHolder()
          + scrollState()
      }
    }
  }
  

  namespace com.gykj.cameramodule {
    namespace adapter {
      class com.gykj.cameramodule.adapter.ImgFolderAdapter.Holder {
          - ivImage : ImageView
          - llParent : RelativeLayout
          - tvImageDirCount : TextView
          - tvImageDirName : TextView
          + Holder()
          + onClick()
          + setData()
      }
    }
  }
  

  namespace com.gykj.cameramodule {
    namespace adapter {
      class com.gykj.cameramodule.adapter.ImgPickAdapter {
          - ITEM_CAMERA : int
          - ITEM_IMAGE : int
          - _chooseList : List<Integer>
          - cbImageLastCheck : CheckBox
          - isBatch : boolean
          - parentPath : String
          + ImgPickAdapter()
          + getItemViewType()
          + getParentPath()
          + getPickedItem()
          + isBatch()
          + isPosItemVisible()
          + onCreateViewHolder()
          + scrollState()
          + setBatch()
          + setImgParentPath()
      }
    }
  }
  

  namespace com.gykj.cameramodule {
    namespace adapter {
      class com.gykj.cameramodule.adapter.ImgPickAdapter.HolderCamera {
          - ivCamera : ImageView
          + HolderCamera()
          + onClick()
          + setData()
      }
    }
  }
  

  namespace com.gykj.cameramodule {
    namespace adapter {
      class com.gykj.cameramodule.adapter.ImgPickAdapter.HolderImage {
          - cbImage : CheckBox
          - imgPath : String
          - ivImage : ImageView
          + HolderImage()
          + onClick()
          + onLongClick()
          + setData()
      }
    }
  }
  

  namespace com.gykj.cameramodule {
    namespace adapter {
      class com.gykj.cameramodule.adapter.ViewPagerAdapter {
          {static} - TAG : String
          - mContext : Context
          - mImages : List<ImagePagerBean>
          - view : View
          + ViewPagerAdapter()
          + destroyItem()
          + getCount()
          + getItemPosition()
          + getPrimaryItem()
          + getmImages()
          + instantiateItem()
          + isViewFromObject()
          + setListener()
          + setPrimaryItem()
          + setmImages()
      }
    }
  }
  

  namespace com.gykj.cameramodule {
    namespace adapter {
      interface com.gykj.cameramodule.adapter.ViewPagerAdapter.OnViewPagerAdapterListener {
          {abstract} + onClickListener()
          {abstract} + onLongClickListener()
      }
    }
  }
  

  com.gykj.cameramodule.adapter.ImgFolderAdapter -up-|> com.gykj.base.adapter.BaseRecycleAdapter
  com.gykj.cameramodule.adapter.ImgFolderAdapter +-down- com.gykj.cameramodule.adapter.ImgFolderAdapter.Holder
  com.gykj.cameramodule.adapter.ImgFolderAdapter.Holder .up.|> android.view.View.OnClickListener
  com.gykj.cameramodule.adapter.ImgFolderAdapter.Holder -up-|> com.gykj.base.adapter.BaseViewHolder
  com.gykj.cameramodule.adapter.ImgPickAdapter -up-|> com.gykj.base.adapter.BaseRecycleAdapter
  com.gykj.cameramodule.adapter.ImgPickAdapter +-down- com.gykj.cameramodule.adapter.ImgPickAdapter.HolderCamera
  com.gykj.cameramodule.adapter.ImgPickAdapter +-down- com.gykj.cameramodule.adapter.ImgPickAdapter.HolderImage
  com.gykj.cameramodule.adapter.ImgPickAdapter.HolderCamera .up.|> android.view.View.OnClickListener
  com.gykj.cameramodule.adapter.ImgPickAdapter.HolderCamera -up-|> com.gykj.base.adapter.BaseViewHolder
  com.gykj.cameramodule.adapter.ImgPickAdapter.HolderImage .up.|> android.view.View.OnClickListener
  com.gykj.cameramodule.adapter.ImgPickAdapter.HolderImage .up.|> android.view.View.OnLongClickListener
  com.gykj.cameramodule.adapter.ImgPickAdapter.HolderImage -up-|> com.gykj.base.adapter.BaseViewHolder
  com.gykj.cameramodule.adapter.ViewPagerAdapter -up-|> androidx.viewpager.widget.PagerAdapter
  com.gykj.cameramodule.adapter.ViewPagerAdapter o-- com.gykj.cameramodule.adapter.ViewPagerAdapter.OnViewPagerAdapterListener : mListener
  com.gykj.cameramodule.adapter.ViewPagerAdapter +-down- com.gykj.cameramodule.adapter.ViewPagerAdapter.OnViewPagerAdapterListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
