@startuml

title __ENTITY's Class Diagram__\n

  namespace com.gykj.grandphotos {
    namespace models.album {
      namespace entity {
        class com.gykj.grandphotos.models.album.entity.Album {
            + albumItems : ArrayList<AlbumItem>
            - hasAlbumItems : LinkedHashMap<String, AlbumItem>
            + Album()
            + addAlbumItem()
            + clear()
            + getAlbumItem()
            + getAlbumItem()
            + isEmpty()
            - addAlbumItem()
        }
      }
    }
  }
  

  namespace com.gykj.grandphotos {
    namespace models.album {
      namespace entity {
        class com.gykj.grandphotos.models.album.entity.AlbumItem {
            + coverImagePath : String
            + coverImageUri : Uri
            + folderPath : String
            + name : String
            + photos : ArrayList<GrandPhotoBean>
            + addImageItem()
            + addImageItem()
            ~ AlbumItem()
        }
      }
    }
  }
  

  namespace com.gykj.grandphotos {
    namespace models.album {
      namespace entity {
        class com.gykj.grandphotos.models.album.entity.GrandPhotoBean {
            {static} + CREATOR : Creator<GrandPhotoBean>
            + height : int
            + isClick : boolean
            + name : String
            + orientation : int
            + path : String
            + selPos : int
            + selected : boolean
            + selectedOriginal : boolean
            + size : long
            + time : long
            + type : String
            + uri : Uri
            + width : int
            {static} - TAG : String
            - animateTime : long
            - botSelect : boolean
            - fromDegree : int
            - rotateDegree : int
            + GrandPhotoBean()
            + describeContents()
            + equals()
            + getAnimateTime()
            + getFromDegree()
            + getRotateDegree()
            + initFromDegree()
            + isBotSelect()
            + setAnimateTime()
            + setBotSelect()
            + setFromDegree()
            + setRotateDegree()
            + toString()
            + writeToParcel()
            # GrandPhotoBean()
        }
      }
    }
  }
  

  com.gykj.grandphotos.models.album.entity.GrandPhotoBean .up.|> android.os.Parcelable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
