@startuml

title __ADAPTER's Class Diagram__\n

  namespace com.grantch.addressselectview {
    namespace adapter {
      class com.grantch.addressselectview.adapter.AddreassSelectorAdapter {
          {static} + VIEW_TYPE_ITEM_TITLE : int
          {static} - VIEW_TYPE_ITEM_CONTENT : int
          - mContentSize : float
          - mSelectedColor : int
          - mUnSelectedColor : int
          - selectPos : int
          + AddreassSelectorAdapter()
          + getItemViewType()
          + getPositionByTitel()
          + getSelectPos()
          + isPinnedPosition()
          + isPosItemVisible()
          + onBindViewHolder()
          + onCreateViewHolder()
          + scrollState()
          + setContentSize()
          + setSelectColors()
          + setTitleSize()
          - setSelectorColor()
      }
    }
  }
  

  namespace com.grantch.addressselectview {
    namespace adapter {
      class com.grantch.addressselectview.adapter.AddreassSelectorAdapter.ContentHolder {
          ~ imageViewCheckMark : ImageView
          ~ rlParent : RelativeLayout
          ~ tvAddress : TextView
          + ContentHolder()
          + setData()
      }
    }
  }
  

  namespace com.grantch.addressselectview {
    namespace adapter {
      class com.grantch.addressselectview.adapter.AddreassSelectorAdapter.TitleHolder {
          ~ mTextTitle : TextView
          + TitleHolder()
          + setData()
      }
    }
  }
  

  namespace com.grantch.addressselectview {
    namespace adapter {
      class com.grantch.addressselectview.adapter.AddressViewAdapter {
          - mDatas : List<AddressBean>
          + AddressViewAdapter()
          + clearDefultSelected()
          + currentLevelSelected()
          + getmMaxLevel()
          + getmMinLevel()
          + recoverLevelData()
          + saveSelectedItem()
          + setDefultSelectItem()
          + setLevelDatas()
          + setMaxLevel()
          + setMinLevel()
          + setNextLevelDatas()
          + setViewLevelSelectedListener()
          + setmCurrentLevelDatas()
      }
    }
  }
  

  namespace com.grantch.addressselectview {
    namespace adapter {
      interface com.grantch.addressselectview.adapter.AddressViewAdapter.ViewLevelSelectedListener {
          {abstract} + seleted()
      }
    }
  }
  

  com.grantch.addressselectview.adapter.AddreassSelectorAdapter -up-|> com.grantch.addressselectview.base.BaseRecycleAdapter
  com.grantch.addressselectview.adapter.AddreassSelectorAdapter +-down- com.grantch.addressselectview.adapter.AddreassSelectorAdapter.ContentHolder
  com.grantch.addressselectview.adapter.AddreassSelectorAdapter +-down- com.grantch.addressselectview.adapter.AddreassSelectorAdapter.TitleHolder
  com.grantch.addressselectview.adapter.AddreassSelectorAdapter.ContentHolder -up-|> com.grantch.addressselectview.base.BaseViewHolder
  com.grantch.addressselectview.adapter.AddreassSelectorAdapter.TitleHolder -up-|> com.grantch.addressselectview.base.BaseViewHolder
  com.grantch.addressselectview.adapter.AddressViewAdapter o-- com.grantch.addressselectview.view.AddressView : mAddressView
  com.grantch.addressselectview.adapter.AddressViewAdapter o-- com.grantch.addressselectview.data.LevelType : mCurrentLevel
  com.grantch.addressselectview.adapter.AddressViewAdapter o-- com.grantch.addressselectview.data.LevelType : mMaxLevel
  com.grantch.addressselectview.adapter.AddressViewAdapter o-- com.grantch.addressselectview.data.LevelType : mMinLevel
  com.grantch.addressselectview.adapter.AddressViewAdapter o-- com.grantch.addressselectview.adapter.AddressViewAdapter.ViewLevelSelectedListener : mViewLevelSelectedListener
  com.grantch.addressselectview.adapter.AddressViewAdapter +-down- com.grantch.addressselectview.adapter.AddressViewAdapter.ViewLevelSelectedListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
