@startuml

title __MAPS's Class Diagram__\n

  namespace com.grandtech.mapframe.core {
    namespace maps {
      class com.grandtech.mapframe.core.maps.GMapView {
          - mBaseEditors : Map<GraphicSetting, BaseEditor>
          - mMapBoxMap : MapboxMap
          + GMapView()
          + GMapView()
          + GMapView()
          + GMapView()
          + GMapView()
          + GMapView()
          + addEditor()
          + addOnMapTouchListener()
          + addSelectChangeListening()
          + addSketchGeometry()
          + clearSelectSetAndRender()
          + clearSketch()
          + getBaseEditor()
          + getBaseEditors()
          + getGc()
          + getGcQueryLayerId()
          + getMapBoxMap()
          + getMarkerManager()
          + getMarkerViewManager()
          + getOfflineDataBaseHandler()
          + getSelectSet()
          + getSketchGeometry()
          + getSketchType()
          + getStyleLayerManager()
          + init()
          + initSelection()
          + initSelection()
          + initSelection()
          + isStartSketch()
          + moveToCurrentLocation()
          + moveToLocation()
          + moveToLocation()
          + moveToLocation()
          + moveToLocation()
          + onBoxMapReady()
          + onDestroy()
          + onMapReady()
          + removeChangeListening()
          + removeOnMapTouchListener()
          + selectFeatureByPoint()
          + setIOnAfterSlideListener()
          + setLocation()
          + setMapEvent()
          + setSelectSetting()
          + setSelectSetting()
          + sketchAddScreenCenterPoint()
          + sketchReDo()
          + sketchUnDo()
          + startSketch()
          + stopSketch()
          - setOnTouchListener()
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace maps {
      interface com.grandtech.mapframe.core.maps.IOnMapReady {
          {abstract} + onBoxMapReady()
      }
    }
  }
  

  com.grandtech.mapframe.core.maps.GMapView .up.|> com.grandtech.mapframe.core.rules.Rules
  com.grandtech.mapframe.core.maps.GMapView .up.|> com.mapbox.mapboxsdk.maps.OnMapReadyCallback
  com.grandtech.mapframe.core.maps.GMapView -up-|> com.mapbox.mapboxsdk.maps.MapView
  com.grandtech.mapframe.core.maps.GMapView o-- com.grandtech.mapframe.core.event.IMapEvent : mBeforeSketchEvent
  com.grandtech.mapframe.core.maps.GMapView o-- com.grandtech.mapframe.core.maps.IOnMapReady : mIOnMapReady
  com.grandtech.mapframe.core.maps.GMapView o-- com.grandtech.mapframe.core.marker.LocView : mLocView
  com.grandtech.mapframe.core.maps.GMapView o-- com.grandtech.mapframe.core.event.MapEventDispatch : mMapEventDispatch
  com.grandtech.mapframe.core.maps.GMapView o-- com.grandtech.mapframe.core.marker.MarkerManager : mMarkerManager
  com.grandtech.mapframe.core.maps.GMapView o-- com.grandtech.mapframe.core.marker.MarkerViewManager : mMarkerViewManager
  com.grandtech.mapframe.core.maps.GMapView o-- com.grandtech.mapframe.core.offline.OfflineDataBaseHandler : mOfflineDataBaseHandler
  com.grandtech.mapframe.core.maps.GMapView o-- com.grandtech.mapframe.core.select.SelectionSet : mSelectionSet
  com.grandtech.mapframe.core.maps.GMapView o-- com.grandtech.mapframe.core.sketch.SketchAnnotations : mSketchAnnotations
  com.grandtech.mapframe.core.maps.GMapView o-- com.grandtech.mapframe.core.sketch.SketchSlideAnnotations : mSketchSlideAnnotations
  com.grandtech.mapframe.core.maps.GMapView o-- com.grandtech.mapframe.core.layer.StyleLayerManager : mStyleLayerManager


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
