@startuml

title __UTIL's Class Diagram__\n

  namespace com.grandtech.mapframe.ui {
    namespace util {
      class com.grandtech.mapframe.ui.util.LayoutTraverser {
          {static} + build()
          + traverse()
          - LayoutTraverser()
      }
    }
  }
  

  namespace com.grandtech.mapframe.ui {
    namespace util {
      interface com.grandtech.mapframe.ui.util.LayoutTraverser.Processor {
          {abstract} + process()
      }
    }
  }
  

  namespace com.grandtech.mapframe.ui {
    namespace util {
      class com.grandtech.mapframe.ui.util.MeasureUtil {
          {static} + dp2px()
          {static} + px2dp()
      }
    }
  }
  

  namespace com.grandtech.mapframe.ui {
    namespace util {
      class com.grandtech.mapframe.ui.util.ViewsTreeUtil {
          {static} + find()
          {static} + find()
          {static} + findT()
          {static} + getAllChildViews()
          {static} + hasView()
          - ViewsTreeUtil()
      }
    }
  }
  

  namespace com.grandtech.mapframe.ui {
    namespace util {
      class com.grandtech.mapframe.ui.util.ViewsTreeUtil.FinderByTag {
          - searchTag : Object
          - views : List<View>
          + process()
          - FinderByTag()
          - getViews()
      }
    }
  }
  

  namespace com.grandtech.mapframe.ui {
    namespace util {
      class com.grandtech.mapframe.ui.util.ViewsTreeUtil.FinderByType {
          - type : Class<T>
          - views : List<T>
          + getViews()
          + process()
          - FinderByType()
      }
    }
  }
  

  com.grandtech.mapframe.ui.util.LayoutTraverser o-- com.grandtech.mapframe.ui.util.LayoutTraverser.Processor : processor
  com.grandtech.mapframe.ui.util.LayoutTraverser +-down- com.grandtech.mapframe.ui.util.LayoutTraverser.Processor
  com.grandtech.mapframe.ui.util.ViewsTreeUtil +-down- com.grandtech.mapframe.ui.util.ViewsTreeUtil.FinderByTag
  com.grandtech.mapframe.ui.util.ViewsTreeUtil +-down- com.grandtech.mapframe.ui.util.ViewsTreeUtil.FinderByType
  com.grandtech.mapframe.ui.util.ViewsTreeUtil.FinderByTag .up.|> com.grandtech.mapframe.ui.util.LayoutTraverser.Processor
  com.grandtech.mapframe.ui.util.ViewsTreeUtil.FinderByType .up.|> com.grandtech.mapframe.ui.util.LayoutTraverser.Processor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
