@startuml

title __SIGNATURE's Class Diagram__\n

  namespace com.gykj.signature {
    class com.gykj.signature.BitmapUtil {
        {static} + byte2File()
    }
  }
  

  namespace com.gykj.signature {
    class com.gykj.signature.LinePathView {
        {static} - TAG : String
        - cacheCanvas : Canvas
        - cachebBitmap : Bitmap
        - isTouched : boolean
        - mBackColor : int
        - mContext : Context
        - mGesturePaint : Paint
        - mPaintWidth : int
        - mPath : Path
        - mPenColor : int
        - mX : float
        - mY : float
        + LinePathView()
        + LinePathView()
        + LinePathView()
        + clear()
        + getBitMap()
        + getBytes()
        + getTouched()
        + init()
        + onTouchEvent()
        + save()
        + save()
        + saveImg()
        + setBackColor()
        + setPaintWidth()
        + setPenColor()
        # onDraw()
        # onSizeChanged()
        - clearBlank()
        - touchDown()
        - touchMove()
    }
  }
  

  namespace com.gykj.signature {
    class com.gykj.signature.SignActivity {
        {static} + FAIL : int
        {static} + OK : int
        - _toolbar : Toolbar
        - btnClear : Button
        - btnConfirm : Button
        - colorBtnNormal : String
        - colorBtnPressed : String
        - ivBack : ImageView
        - signPath : String
        + onClick()
        # initialize()
        # onCreate()
        # registerEvent()
    }
  }
  

  com.gykj.signature.LinePathView -up-|> android.view.View
  com.gykj.signature.SignActivity .up.|> android.view.View.OnClickListener
  com.gykj.signature.SignActivity -up-|> com.trello.rxlifecycle2.components.support.RxAppCompatActivity
  com.gykj.signature.SignActivity o-- com.gykj.signature.LinePathView : lpvSign


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
