@startuml

title __MARKER's Class Diagram__\n

  namespace com.grandtech.mapframe.core {
    namespace marker {
      class com.grandtech.mapframe.core.marker.LocView {
          - bitmap : Bitmap
          - directorBitmap : Bitmap
          - geomagnetic : float[]
          - gravity : float[]
          - iconRes : int
          - lat : Double
          - lon : Double
          - obtainPosition : boolean
          - paint : Paint
          - paint1 : Paint
          - rotate : float
          - rotateBitmap : Bitmap
          - sensorManager : SensorManager
          - x : float
          - y : float
          + LocView()
          + destroyDrawingCache()
          + getLat()
          + getLon()
          + getValue()
          + onAccuracyChanged()
          + onMove()
          + onMoveBegin()
          + onMoveEnd()
          + onSensorChanged()
          + setLocation()
          # onDraw()
          - draw()
          - init()
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace marker {
      class com.grandtech.mapframe.core.marker.MarkerManager {
          - mMarkerGroups : Map<String, List<Marker>>
          - mMarkerMap : Map<String, Marker>
          + MarkerManager()
          + addMarker()
          + addMarkers()
          + removeAllMarker()
          + removeMarker()
          + removeMarker()
          + removeMarkerGroup()
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace marker {
      class com.grandtech.mapframe.core.marker.MarkerView {
          - latLng : LatLng
          - markerId : String
          - offsetX : int
          - offsetY : int
          - projection : Projection
          - view : View
          + MarkerView()
          + getMarkerId()
          + getOffsetX()
          + getOffsetY()
          + setLatLng()
          + setMarkerId()
          + setOffsetX()
          + setOffsetY()
          + setOnPositionUpdateListener()
          ~ getView()
          ~ setProjection()
          ~ update()
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace marker {
      interface com.grandtech.mapframe.core.marker.MarkerView.OnPositionUpdateListener {
          {abstract} + onUpdate()
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace marker {
      class com.grandtech.mapframe.core.marker.MarkerViewManager {
          - initialised : boolean
          - markers : List<MarkerView>
          + MarkerViewManager()
          + addMarker()
          + getMarker()
          + onCameraDidChange()
          + onCameraIdle()
          + onCameraWillChange()
          + onDestroy()
          + removeAllMarker()
          + removeMarker()
          + removeMarker()
          - avoid()
          - avoidMarkerView()
          - avoidView()
          - getVisibleView()
          - update()
          - visible()
      }
    }
  }
  

  com.grandtech.mapframe.core.marker.LocView .up.|> android.hardware.SensorEventListener
  com.grandtech.mapframe.core.marker.LocView .up.|> com.mapbox.mapboxsdk.maps.MapboxMap.OnMoveListener
  com.grandtech.mapframe.core.marker.LocView -up-|> android.widget.FrameLayout
  com.grandtech.mapframe.core.marker.LocView o-- com.grandtech.mapframe.core.maps.GMapView : gMapView
  com.grandtech.mapframe.core.marker.MarkerManager .up.|> com.grandtech.mapframe.core.rules.Rules
  com.grandtech.mapframe.core.marker.MarkerManager o-- com.grandtech.mapframe.core.maps.GMapView : mGMapView
  com.grandtech.mapframe.core.marker.MarkerView .up.|> com.grandtech.mapframe.core.rules.Rules
  com.grandtech.mapframe.core.marker.MarkerView o-- com.grandtech.mapframe.core.marker.MarkerView.OnPositionUpdateListener : onPositionUpdateListener
  com.grandtech.mapframe.core.marker.MarkerView +-down- com.grandtech.mapframe.core.marker.MarkerView.OnPositionUpdateListener
  com.grandtech.mapframe.core.marker.MarkerViewManager .up.|> com.grandtech.mapframe.core.rules.Rules
  com.grandtech.mapframe.core.marker.MarkerViewManager .up.|> com.mapbox.mapboxsdk.maps.MapView.OnCameraDidChangeListener
  com.grandtech.mapframe.core.marker.MarkerViewManager .up.|> com.mapbox.mapboxsdk.maps.MapView.OnCameraWillChangeListener
  com.grandtech.mapframe.core.marker.MarkerViewManager .up.|> com.mapbox.mapboxsdk.maps.MapboxMap.OnCameraIdleListener
  com.grandtech.mapframe.core.marker.MarkerViewManager o-- com.grandtech.mapframe.core.maps.GMapView : mapView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
