@startuml

title __OPTION's Class Diagram__\n

  namespace com.grandtech.echart {
    namespace option {
      class com.grandtech.echart.option.EffectOption {
          - effect : Object
          - progress : Integer
          + effect()
          + effect()
          + getEffect()
          + getProgress()
          + getTextStyle()
          + progress()
          + progress()
          + setEffect()
          + setProgress()
          + setTextStyle()
          + textStyle()
          + textStyle()
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace option {
      class com.grandtech.echart.option.NoDataLoadingOption {
          - effect : Object
          - progress : Integer
          - text : String
          - x : Object
          - y : Object
          + effect()
          + effect()
          + effect()
          + effectOption()
          + effectOption()
          + getEffect()
          + getEffectOption()
          + getProgress()
          + getText()
          + getTextStyle()
          + getX()
          + getY()
          + progress()
          + progress()
          + setEffect()
          + setEffectOption()
          + setProgress()
          + setText()
          + setTextStyle()
          + setX()
          + setY()
          + text()
          + text()
          + textStyle()
          + textStyle()
          + x()
          + x()
          + y()
          + y()
      }
    }
  }
  

  com.grandtech.echart.option.EffectOption o-- com.grandtech.echart.style.TextStyle : textStyle
  com.grandtech.echart.option.NoDataLoadingOption o-- com.grandtech.echart.option.EffectOption : effectOption
  com.grandtech.echart.option.NoDataLoadingOption o-- com.grandtech.echart.style.TextStyle : textStyle


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
