@startuml

title __PICKER's Class Diagram__\n

  namespace com.gykj.selectlinearlayout {
    namespace picker {
      class com.gykj.selectlinearlayout.picker.SinglePicker {
          {static} - ITEM_WIDTH_UNKNOWN : int
          - itemStrings : List<String>
          - itemWidth : int
          - items : List<T>
          - label : String
          - onItemPickListener : OnItemPickListener<T>
          - onWheelListener : OnWheelListener<T>
          - selectedItemIndex : int
          + SinglePicker()
          + SinglePicker()
          + addItem()
          + getSelectedIndex()
          + getSelectedItem()
          {static} + getSinglePicker()
          + getWheelView()
          + onSubmit()
          + removeItem()
          + setItemWidth()
          + setItems()
          + setItems()
          + setLabel()
          + setOnItemPickListener()
          + setOnWheelListener()
          + setSelectedIndex()
          + setSelectedItem()
          + setWheelViewShowItem()
          # makeCenterView()
          - formatToString()
      }
    }
  }
  

  namespace com.gykj.selectlinearlayout {
    namespace picker {
      interface com.gykj.selectlinearlayout.picker.SinglePicker.OnItemPickListener {
          {abstract} + onItemPicked()
      }
    }
  }
  

  namespace com.gykj.selectlinearlayout {
    namespace picker {
      interface com.gykj.selectlinearlayout.picker.SinglePicker.OnWheelListener {
          {abstract} + onWheeled()
      }
    }
  }
  

  namespace com.gykj.selectlinearlayout {
    namespace picker {
      abstract class com.gykj.selectlinearlayout.picker.WheelPicker {
          # cycleDisable : boolean
          # labelTextColor : int
          # lineSpaceMultiplier : float
          # offset : int
          # textColorFocus : int
          # textColorNormal : int
          # textPadding : int
          # textSize : int
          # textSizeAutoFit : boolean
          # typeface : Typeface
          # useWeight : boolean
          + WheelPicker()
          + getContentView()
          + setCycleDisable()
          + setDividerColor()
          + setDividerConfig()
          + setDividerRatio()
          + setDividerVisible()
          + setLabelTextColor()
          + setLineColor()
          + setLineConfig()
          + setLineSpaceMultiplier()
          + setLineVisible()
          + setOffset()
          + setPadding()
          + setShadowColor()
          + setShadowColor()
          + setShadowVisible()
          + setTextColor()
          + setTextColor()
          + setTextPadding()
          + setTextSize()
          + setTextSizeAutoFit()
          + setUseWeight()
          # createLabelView()
          # createWheelView()
      }
    }
  }
  

  com.gykj.selectlinearlayout.picker.SinglePicker -up-|> com.gykj.selectlinearlayout.picker.WheelPicker
  com.gykj.selectlinearlayout.picker.SinglePicker o-- com.gykj.selectlinearlayout.view.WheelView : wheelView
  com.gykj.selectlinearlayout.picker.SinglePicker +-down- com.gykj.selectlinearlayout.picker.SinglePicker.OnItemPickListener
  com.gykj.selectlinearlayout.picker.SinglePicker +-down- com.gykj.selectlinearlayout.picker.SinglePicker.OnWheelListener
  com.gykj.selectlinearlayout.picker.WheelPicker -up-|> com.gykj.selectlinearlayout.popup.ConfirmPopup
  com.gykj.selectlinearlayout.picker.WheelPicker o-- com.gykj.selectlinearlayout.view.WheelView.DividerConfig : dividerConfig


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
