@startuml

title __EVENT's Class Diagram__\n

  namespace com.grandtech.mapframe.core {
    namespace event {
      interface com.grandtech.mapframe.core.event.IMapEvent {
          {abstract} + onCameraIdle()
          {abstract} + onCameraMove()
          {abstract} + onCameraMoveCanceled()
          {abstract} + onCameraMoveStarted()
          {abstract} + onCompassAnimation()
          {abstract} + onCompassAnimationFinished()
          {abstract} + onFling()
          {abstract} + onFpsChanged()
          {abstract} + onMapClick()
          {abstract} + onMapLongClick()
          {abstract} + onMarkerClick()
          {abstract} + onPolygonClick()
          {abstract} + onPolylineClick()
          {abstract} + onScroll()
          {abstract} + onTouchCancel()
          {abstract} + onTouchMoving()
          {abstract} + onTouchStart()
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace event {
      class com.grandtech.mapframe.core.event.MapEventDispatch {
          + MapEventDispatch()
          + getCurIMapEvent()
          + getSketchMapEvnet()
          + onCameraIdle()
          + onCameraMove()
          + onCameraMoveCanceled()
          + onCameraMoveStarted()
          + onFling()
          + onFpsChanged()
          + onMapClick()
          + onMapLongClick()
          + onMarkerClick()
          + onPolygonClick()
          + onPolylineClick()
          + onTouchCancel()
          + onTouchMoving()
          + onTouchStart()
          + setCurIMapEvent()
          + setSketchMapEvnet()
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace event {
      abstract class com.grandtech.mapframe.core.event.MapExtentEvent {
          - mOnTouchListenerList : List<OnTouchListener>
          + MapExtentEvent()
          + addOnTouchListener()
          + onTouch()
          {abstract} + onTouchCancel()
          {abstract} + onTouchMoving()
          {abstract} + onTouchStart()
          + removeOnTouchListener()
      }
    }
  }
  

  com.grandtech.mapframe.core.event.MapEventDispatch .up.|> com.mapbox.mapboxsdk.maps.MapboxMap.OnCameraIdleListener
  com.grandtech.mapframe.core.event.MapEventDispatch .up.|> com.mapbox.mapboxsdk.maps.MapboxMap.OnCameraMoveCanceledListener
  com.grandtech.mapframe.core.event.MapEventDispatch .up.|> com.mapbox.mapboxsdk.maps.MapboxMap.OnCameraMoveListener
  com.grandtech.mapframe.core.event.MapEventDispatch .up.|> com.mapbox.mapboxsdk.maps.MapboxMap.OnCameraMoveStartedListener
  com.grandtech.mapframe.core.event.MapEventDispatch .up.|> com.mapbox.mapboxsdk.maps.MapboxMap.OnFlingListener
  com.grandtech.mapframe.core.event.MapEventDispatch .up.|> com.mapbox.mapboxsdk.maps.MapboxMap.OnFpsChangedListener
  com.grandtech.mapframe.core.event.MapEventDispatch .up.|> com.mapbox.mapboxsdk.maps.MapboxMap.OnMapClickListener
  com.grandtech.mapframe.core.event.MapEventDispatch .up.|> com.mapbox.mapboxsdk.maps.MapboxMap.OnMapLongClickListener
  com.grandtech.mapframe.core.event.MapEventDispatch .up.|> com.mapbox.mapboxsdk.maps.MapboxMap.OnMarkerClickListener
  com.grandtech.mapframe.core.event.MapEventDispatch .up.|> com.mapbox.mapboxsdk.maps.MapboxMap.OnPolygonClickListener
  com.grandtech.mapframe.core.event.MapEventDispatch .up.|> com.mapbox.mapboxsdk.maps.MapboxMap.OnPolylineClickListener
  com.grandtech.mapframe.core.event.MapEventDispatch -up-|> com.grandtech.mapframe.core.event.MapExtentEvent
  com.grandtech.mapframe.core.event.MapEventDispatch o-- com.grandtech.mapframe.core.event.IMapEvent : mIMapEvent
  com.grandtech.mapframe.core.event.MapEventDispatch o-- com.grandtech.mapframe.core.sketch.SketchMapEvnet : mSketchMapEvnet
  com.grandtech.mapframe.core.event.MapExtentEvent .up.|> android.view.View.OnTouchListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
