LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := sqlite

SQLITE_PATH := $(LOCAL_PATH)/sqlite-amalgamation-3081002

# NOTE the following flags,
#   SQLITE_TEMP_STORE=3 causes all TEMP files to go into RAM. and thats the behavior we want
#   SQLITE_ENABLE_FTS3   enables usage of FTS3 - NOT FTS1 or 2.
#   SQLITE_DEFAULT_AUTOVACUUM=1  causes the databases to be subject to auto-vacuum

common_sqlite_flags := \
            -DSQLITE_HAS_CODEC \
            -DSQLITE_SOUNDEX \
            -DHAVE_USLEEP=1 \
            -DSQLITE_MAX_VARIABLE_NUMBER=99999 \
            -DSQLITE_TEMP_STORE=3 \
            -DSQLITE_THREADSAFE=1 \
            -DSQLITE_DEFAULT_JOURNAL_SIZE_LIMIT=1048576 \
            -DNDEBUG=1 \
            -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 \
            -DSQLITE_ENABLE_LOAD_EXTENSION \
            -DSQLITE_ENABLE_COLUMN_METADATA \
            -DSQLITE_ENABLE_UNLOCK_NOTIFY \
            -DSQLITE_ENABLE_RTREE \
            -DSQLITE_ENABLE_STAT3 \
            -DSQLITE_ENABLE_STAT4 \
            -DSQLITE_ENABLE_JSON1 \
            -DSQLITE_ENABLE_FTS3_PARENTHESIS \
            -DSQLITE_ENABLE_FTS4 \
            -DSQLITE_ENABLE_FTS5 \
            -DSQLCIPHER_CRYPTO_OPENSSL \

			-DNDEBUG=1 \
			-DHAVE_USLEEP=1 \
			-DSQLITE_HAVE_ISNAN \
			-DSQLITE_DEFAULT_JOURNAL_SIZE_LIMIT=1048576 \
			-DSQLITE_THREADSAFE=2 \
			-DSQLITE_TEMP_STORE=3 \
			-DSQLITE_POWERSAFE_OVERWRITE=1 \
			-DSQLITE_DEFAULT_FILE_FORMAT=4 \
			-DSQLITE_DEFAULT_AUTOVACUUM=1 \
			-DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 \
			-DSQLITE_ENABLE_FTS3 \
			-DSQLITE_ENABLE_FTS3_BACKWARDS \
			-DSQLITE_ENABLE_FTS4 \
			-DSQLITE_OMIT_BUILTIN_TEST \
			-DSQLITE_OMIT_COMPILEOPTION_DIAGS \
			-DSQLITE_DEFAULT_FILE_PERMISSIONS=0600
#	-DSQLITE_OMIT_LOAD_EXTENSION

LOCAL_CFLAGS := $(common_sqlite_flags)

LOCAL_EXPORT_C_INCLUDES := $(SQLITE_PATH)

LOCAL_C_INCLUDES := 

LOCAL_SRC_FILES := $(SQLITE_PATH)/sqlite3.c
LOCAL_STATIC_LIBRARIES += static-libcrypto

include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := static-libcrypto
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/openssl/include
LOCAL_SRC_FILES := $(LOCAL_PATH)/openssl/android-libs/$(TARGET_ARCH_ABI)/libcrypto.a
include $(PREBUILT_STATIC_LIBRARY)
