@startuml

title __UTILS's Class Diagram__\n

  namespace com.gykj.utils {
    class com.gykj.utils.BitmapUtils {
        {static} + addMark2Bitmap()
        {static} + addMark2Bitmap()
        {static} + addMark2BitmapEx()
        {static} + addWatermarkBitmap()
        + bitmap2Array()
        {static} + bitmap2File()
        {static} + bitmap2File()
        {static} + bitmap2File()
        {static} + bitmapCropWithRect()
        {static} + byte2File()
        {static} + getBitmapFromHttp()
        {static} + getBitmapFromSDPath()
        {static} + getImageThumbnail()
        {static} + rotatingBitmap()
    }
  }
  

  namespace com.gykj.utils {
    class com.gykj.utils.DateUtils {
        {static} - ONE_DAY : long
        {static} - weeks : int
        {static} + LastMonth()
        {static} + add()
        {static} + addDay()
        {static} + compareDate()
        {static} + compareDayHourMinite()
        {static} + compareMonth()
        {static} + date2Str()
        {static} + dateToLong()
        {static} + getCurrentMonth()
        {static} + getCurrentTime()
        {static} + getCurrentYear()
        {static} + getCurrentYear()
        {static} + getDate()
        {static} + getDayOfWeek()
        {static} + getDistanceString()
        {static} + getDistanceTime()
        {static} + getFirstDayOfMonth()
        {static} + getLastDayOfMonth()
        {static} + getMonth()
        {static} + getPreviousWeekSunday()
        {static} + getPreviousWeekday()
        {static} + getTimeZone()
        {static} + getYearMonth()
        {static} + getYearMonthDay()
        {static} + lastYear()
        {static} + lately30Day()
        {static} + lately7Day()
        {static} + strToDate()
        {static} + stringToDate()
        {static} + stringToLong()
        {static} + subDay()
        {static} + yesterday()
        {static} - getMondayPlus()
    }
  }
  

  namespace com.gykj.utils {
    class com.gykj.utils.FileUtils {
    }
  }
  

  namespace com.gykj.utils {
    class com.gykj.utils.GisConvertUtils {
        {static} + a : double
        {static} - ee : double
        {static} - pi : double
        {static} + bd09_To_Gcj02()
        {static} + bd09_To_Gps84()
        {static} + changeToDFM()
        {static} + dfm2LatLng()
        {static} + gcj02_To_Bd09()
        {static} + gcj02_To_Gps84()
        {static} + gps84_To_Dd09()
        {static} + gps84_To_Gcj02()
        {static} + outOfChina()
        {static} + transform()
        {static} + transformLat()
        {static} + transformLon()
    }
  }
  

  namespace com.gykj.utils {
    class com.gykj.utils.ScreenUtils {
    }
  }
  

  namespace com.gykj.utils {
    class com.gykj.utils.ThreadUtils {
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
