@startuml

title __V1's Class Diagram__\n

  namespace com.gykj.locationservice {
    namespace baseservices.v1 {
      abstract class com.gykj.locationservice.baseservices.v1.BaseFrontService {
          {static} # NOTIFICATION_ID : int
          {static} # TAG : String
          # contentView : RemoteViews
          # mNM : NotificationManager
          # mReflectFlg : boolean
          # mSetForeground : Method
          {static} # mSetForegroundSignature : Class<?>[]
          # mStartForeground : Method
          {static} # mStartForegroundSignature : Class<?>[]
          # mStopForeground : Method
          {static} # mStopForegroundSignature : Class<?>[]
          # manager : NotificationManager
          # noticeId : int
          # notification : Notification
          - mSetForegroundArgs : Object[]
          - mStartForegroundArgs : Object[]
          - mStopForegroundArgs : Object[]
          + onBind()
          + onCreate()
          + onDestroy()
          + onStartCommand()
          + setIBaseServiceLifeCycle()
          # createFrontNotice()
          {abstract} # setNoticeStyle()
          # startForegroundCompat()
          ~ invokeMethod()
          ~ stopForegroundCompat()
      }
    }
  }
  

  namespace com.gykj.locationservice {
    namespace baseservices.v1 {
      abstract class com.gykj.locationservice.baseservices.v1.BaseServiceBinder {
      }
    }
  }
  

  com.gykj.locationservice.baseservices.v1.BaseFrontService -up-|> android.app.Service
  com.gykj.locationservice.baseservices.v1.BaseFrontService o-- com.gykj.locationservice.baseservices.v1.i.IBaseServiceLifeCycle : iBaseServiceLifeCycle
  com.gykj.locationservice.baseservices.v1.BaseServiceBinder .up.|> com.gykj.locationservice.baseservices.v1.i.IServiceBinder
  com.gykj.locationservice.baseservices.v1.BaseServiceBinder -up-|> android.os.Binder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
