@startuml

title __GAUGE's Class Diagram__\n

  namespace com.grandtech.echart {
    namespace series {
      namespace gauge {
        class com.grandtech.echart.series.gauge.Detail {
            - backgroundColor : String
            - borderColor : String
            - borderWidth : Integer
            - formatter : String
            - height : Object
            - offsetCenter : Object
            {static} - serialVersionUID : long
            - show : Boolean
            - width : Object
            + backgroundColor()
            + backgroundColor()
            + borderColor()
            + borderColor()
            + borderWidth()
            + borderWidth()
            + formatter()
            + formatter()
            + getBackgroundColor()
            + getBorderColor()
            + getBorderWidth()
            + getFormatter()
            + getHeight()
            + getOffsetCenter()
            + getShow()
            + getTextStyle()
            + getWidth()
            + height()
            + height()
            + offsetCenter()
            + offsetCenter()
            + setBackgroundColor()
            + setBorderColor()
            + setBorderWidth()
            + setFormatter()
            + setHeight()
            + setOffsetCenter()
            + setShow()
            + setTextStyle()
            + setWidth()
            + show()
            + show()
            + textStyle()
            + width()
            + width()
        }
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace series {
      namespace gauge {
        class com.grandtech.echart.series.gauge.Pointer {
            - color : String
            - length : Object
            {static} - serialVersionUID : long
            - width : Object
            + color()
            + color()
            + getColor()
            + getLength()
            + getWidth()
            + length()
            + length()
            + setColor()
            + setLength()
            + setWidth()
            + width()
            + width()
        }
      }
    }
  }
  

  com.grandtech.echart.series.gauge.Detail .up.|> java.io.Serializable
  com.grandtech.echart.series.gauge.Detail o-- com.grandtech.echart.style.TextStyle : textStyle
  com.grandtech.echart.series.gauge.Pointer .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
