@startuml

title __CROP's Class Diagram__\n

  namespace com.baidu.ocr.ui {
    namespace crop {
      class com.baidu.ocr.ui.crop.CropView {
          ~ rotation : int
          - bitmap : Bitmap
          - gestureDetector : GestureDetector
          - matrix : Matrix
          - matrixArray : float[]
          - maximumScale : float
          - onScaleGestureListener : OnScaleGestureListener
          - restrictBound : Rect
          - scaleGestureDetector : ScaleGestureDetector
          - setMinimumScale : float
          + CropView()
          + CropView()
          + CropView()
          + crop()
          + onTouchEvent()
          + rotate()
          + setFilePath()
          + setMaximumScale()
          + setMinimumScale()
          + setRestrictBound()
          # onDraw()
          # onSizeChanged()
          - centerImage()
          - getRestrictedBound()
          - getScale()
          - init()
          - scale()
          - setBitmap()
          - translate()
      }
    }
  }
  

  namespace com.baidu.ocr.ui {
    namespace crop {
      class com.baidu.ocr.ui.crop.FrameOverlayView {
          ~ cornerLength : int
          ~ cornerLineWidth : int
          ~ margin : int
          {static} - CORNER_LEFT_BOTTOM : int
          {static} - CORNER_LEFT_TOP : int
          {static} - CORNER_RIGHT_BOTTOM : int
          {static} - CORNER_RIGHT_TOP : int
          - currentCorner : int
          - eraser : Paint
          - frameRect : RectF
          - gestureDetector : GestureDetector
          - maskColor : int
          - onGestureListener : SimpleOnGestureListener
          - paint : Paint
          - shapeType : int
          - touchRect : RectF
          + FrameOverlayView()
          + FrameOverlayView()
          + FrameOverlayView()
          + getFrameRect()
          + onTouchEvent()
          + setOnFrameChangeListener()
          + setTypeWide()
          # onDraw()
          # onSizeChanged()
          - drawCorners()
          - drawLine()
          - getMinimumFrameHeight()
          - getMinimumFrameWidth()
          - handleDown()
          - handleScale()
          - init()
          - notifyFrameChange()
          - resetFrameRect()
          - scaleTo()
          - translate()
      }
    }
  }
  

  namespace com.baidu.ocr.ui {
    namespace crop {
      interface com.baidu.ocr.ui.crop.FrameOverlayView.OnFrameChangeListener {
          {abstract} + onFrameChange()
      }
    }
  }
  

  com.baidu.ocr.ui.crop.CropView -up-|> android.view.View
  com.baidu.ocr.ui.crop.FrameOverlayView -up-|> android.view.View
  com.baidu.ocr.ui.crop.FrameOverlayView o-- com.baidu.ocr.ui.crop.FrameOverlayView.OnFrameChangeListener : onFrameChangeListener
  com.baidu.ocr.ui.crop.FrameOverlayView +-down- com.baidu.ocr.ui.crop.FrameOverlayView.OnFrameChangeListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
