@startuml

title __PROJ4's Class Diagram__\n

  namespace org {
    namespace proj4 {
      class org.proj4.GridInfo {
          + fileName : String
          + gridName : String
          + gridOffset : int
      }
    }
  }
  

  namespace org {
    namespace proj4 {
      class org.proj4.GridInfo.CTable {
          + cellLambda : double
          + cellPhi : double
          + id : String
          + originLambda : double
          + originPhi : double
          + sizeLambda : int
          + sizePhi : int
      }
    }
  }
  

  namespace org {
    namespace proj4 {
      enum Format {
        CTABLE
        CTABLE2
        GTX
        NTV1
        NTV2
      }
    }
  }
  

  namespace org {
    namespace proj4 {
      class org.proj4.PJ {
          {static} + DIMENSION_MAX : int
          - ptr : long
          + PJ()
          + PJ()
          + getAxisDirections()
          + getDefinition()
          + getEccentricitySquared()
          + getGreenwichLongitude()
          + getLastError()
          + getLinearUnitToMetre()
          + getSemiMajorAxis()
          + getSemiMinorAxis()
          + getType()
          {static} + getVersion()
          {static} + readGridInfo()
          {static} + setDataPath()
          {static} + setSearchPaths()
          + toString()
          + transform()
          # finalize()
          {static} - allocateGeoPJ()
          {static} - allocatePJ()
      }
    }
  }
  

  namespace org {
    namespace proj4 {
      enum Type {
        GEOCENTRIC
        GEOGRAPHIC
        PROJECTED
      }
    }
  }
  

  namespace org {
    namespace proj4 {
      class org.proj4.PJException {
          {static} - serialVersionUID : long
          + PJException()
          + PJException()
      }
    }
  }
  

  org.proj4.GridInfo o-- org.proj4.GridInfo : child
  org.proj4.GridInfo o-- org.proj4.GridInfo.CTable : ctable
  org.proj4.GridInfo o-- org.proj4.GridInfo.Format : format
  org.proj4.GridInfo o-- org.proj4.GridInfo : next
  org.proj4.GridInfo +-down- org.proj4.GridInfo.CTable
  org.proj4.GridInfo +-down- org.proj4.GridInfo.Format
  org.proj4.PJ +-down- org.proj4.PJ.Type


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
