@startuml

title __ACTIVITY's Class Diagram__\n

  namespace com.gykj.base.activity {
    abstract class com.gykj.base.activity.BaseActivity {
        # MANIFEST_CAMERA : String[]
        # MANIFEST_LOCATION : String[]
        # MANIFEST_PHONE_STATE : String[]
        # MANIFEST_STORAGE : String[]
        - iOnActivityResults : List<IOnActivityResult>
        + addIOnActivityResults()
        + checkPermission()
        + checkPermission()
        + onPermissionsAllGranted()
        + onPermissionsDenied()
        + onPermissionsGranted()
        + onRequestPermissionsResult()
        + showLongToast()
        + showToast()
        {abstract} # initClass()
        {abstract} # initialize()
        # onActivityResult()
        # onCreate()
        # onDestroy()
        {abstract} # registerEvent()
    }
  }
  

  namespace com.gykj.base.activity {
    interface com.gykj.base.activity.BaseActivity.CheckPermListener {
        {abstract} + superPermission()
    }
  }
  

  namespace com.gykj.base.activity {
    interface com.gykj.base.activity.IOnActivityResult {
        {abstract} + onActivityResult()
    }
  }
  

  com.gykj.base.activity.BaseActivity .up.|> com.gykj.utils.EasyPermissions.PermissionCallbacks
  com.gykj.base.activity.BaseActivity -up-|> android.app.Activity
  com.gykj.base.activity.BaseActivity o-- com.gykj.base.activity.BaseActivity.CheckPermListener : checkPermListener
  com.gykj.base.activity.BaseActivity +-down- com.gykj.base.activity.BaseActivity.CheckPermListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
