@startuml

title __MAPDEMO's Class Diagram__\n

  namespace com.gradtech.mapframe.mapdemo {
    class com.gradtech.mapframe.mapdemo.SelectionTestActivity {
        - sklzzdk : Button
        - sklzzdkfill : Button
        - splzzdk : Button
        - splzzdkfill : Button
        + onMapClick()
        # onCreate()
        - clearEvent()
    }
  }
  

  namespace com.gradtech.mapframe.mapdemo {
    class com.gradtech.mapframe.mapdemo.SketchTestActivity {
        - addgeo : Button
        - flMainFrame : FrameLayout
        - jd : Button
        - js : Button
        - ks : Button
        - ksdhm : Button
        - ksdhx : Button
        - qk : Button
        - redo : Button
        - undo : Button
        + onLowMemory()
        + onMapClick()
        # onCreate()
        # onDestroy()
        # onStart()
        # onStop()
    }
  }
  

  com.gradtech.mapframe.mapdemo.SelectionTestActivity .up.|> com.gradtech.mapframev10.core.event.IMapEvent
  com.gradtech.mapframe.mapdemo.SelectionTestActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.gradtech.mapframe.mapdemo.SelectionTestActivity o-- com.gradtech.mapframev10.core.maps.GMapView : gMapView
  com.gradtech.mapframe.mapdemo.SketchTestActivity .up.|> com.gradtech.mapframev10.core.event.IMapEvent
  com.gradtech.mapframe.mapdemo.SketchTestActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.gradtech.mapframe.mapdemo.SketchTestActivity o-- com.gradtech.mapframev10.core.maps.GMapView : gMapView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
