@startuml

title __V2's Class Diagram__\n

  namespace com.gykj.locationservice {
    namespace baseservices.v2 {
      abstract class com.gykj.locationservice.baseservices.v2.BaseService {
          # frontServiceNotification : Notification
          # frontServiceNotificationContent : String
          # frontServiceNotificationId : int
          # frontServiceNotificationTitle : String
          # isFrontService : boolean
          # notificationCompatBuilder : Builder
          # notificationManager : NotificationManager
          # serviceRunningInCommand : boolean
          # serviceRunningInCreate : boolean
          {static} - NOTIFICATION_ID : int
          - mReflectFlg : boolean
          - mSetForeground : Method
          - mSetForegroundArgs : Object[]
          {static} - mSetForegroundSignature : Class<?>[]
          - mStartForeground : Method
          - mStartForegroundArgs : Object[]
          {static} - mStartForegroundSignature : Class<?>[]
          - mStopForeground : Method
          - mStopForegroundArgs : Object[]
          {static} - mStopForegroundSignature : Class<?>[]
          + onBind()
          + onCreate()
          + onDestroy()
          + onStartCommand()
          + setIBaseServiceLifeCycle()
          # createFrontNotice()
          {abstract} # doCommandInBackGrounding()
          {abstract} # doCommandInBackGroundingInitialize()
          # doInBackGrounded()
          {abstract} # doInBackGrounding()
          {abstract} # doInBackGroundingInitialize()
          # frontServiceNoticeStyle()
          # startForegroundCompat()
          ~ invokeMethod()
          ~ stopForegroundCompat()
      }
    }
  }
  

  com.gykj.locationservice.baseservices.v2.BaseService -up-|> android.app.Service
  com.gykj.locationservice.baseservices.v2.BaseService o-- com.gykj.locationservice.baseservices.v2.binder.BaseServiceBinder : baseServiceBinder
  com.gykj.locationservice.baseservices.v2.BaseService o-- com.gykj.locationservice.baseservices.v2.i.IBaseServiceLifeCycle : iBaseServiceLifeCycle


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
