@startuml

title __OTHER's Class Diagram__\n

  namespace com.grandtech.echart {
    namespace series {
      namespace other {
        class com.grandtech.echart.series.other.Force {
            - edgeLength : Integer
            - gravity : Integer
            - initLayout : Object
            - layoutAnimation : Boolean
            - repulsion : Integer
            {static} - serialVersionUID : long
            + edgeLength()
            + edgeLength()
            + getEdgeLength()
            + getGravity()
            + getInitLayout()
            + getLayoutAnimation()
            + getRepulsion()
            + gravity()
            + gravity()
            + initLayout()
            + initLayout()
            + initLayout()
            + initLayout()
            + layoutAnimation()
            + layoutAnimation()
            + repulsion()
            + repulsion()
            + setEdgeLength()
            + setGravity()
            + setInitLayout()
            + setLayoutAnimation()
            + setRepulsion()
        }
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace series {
      namespace other {
        class com.grandtech.echart.series.other.Level {
            - childrenVisibleMin : Double
            - color : Object[]
            - colorAlpha : Object[]
            - colorMappingBy : Object
            - colorSaturation : Double
            {static} - serialVersionUID : long
            - visibleMin : Double
            - visualDimension : Integer
            + childrenVisibleMin()
            + childrenVisibleMin()
            + color()
            + color()
            + colorAlpha()
            + colorAlpha()
            + colorMappingBy()
            + colorMappingBy()
            + colorMappingBy()
            + colorSaturation()
            + colorSaturation()
            + getChildrenVisibleMin()
            + getColor()
            + getColorAlpha()
            + getColorMappingBy()
            + getColorSaturation()
            + getItemStyle()
            + getLabel()
            + getVisibleMin()
            + getVisualDimension()
            + itemStyle()
            + itemStyle()
            + label()
            + label()
            + setChildrenVisibleMin()
            + setColor()
            + setColorAlpha()
            + setColorMappingBy()
            + setColorSaturation()
            + setItemStyle()
            + setLabel()
            + setVisibleMin()
            + setVisualDimension()
            + visibleMin()
            + visibleMin()
            + visualDimension()
            + visualDimension()
        }
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace series {
      namespace other {
        class com.grandtech.echart.series.other.RippleEffect {
            - period : Integer
            - scale : Double
            {static} - serialVersionUID : long
            + brushType()
            + brushType()
            + getBrushType()
            + getPeriod()
            + getScale()
            + period()
            + period()
            + scale()
            + scale()
            + setBrushType()
            + setPeriod()
            + setScale()
        }
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace series {
      namespace other {
        class com.grandtech.echart.series.other.RootLocation {
            {static} - serialVersionUID : long
            - x : Object
            - y : Object
            + RootLocation()
            + RootLocation()
            + getX()
            + getY()
            + setX()
            + setY()
            + x()
            + x()
            + x()
            + x()
            + x()
            + y()
            + y()
            + y()
            + y()
            + y()
        }
      }
    }
  }
  

  com.grandtech.echart.series.other.Force .up.|> java.io.Serializable
  com.grandtech.echart.series.other.Level .up.|> java.io.Serializable
  com.grandtech.echart.series.other.Level o-- com.grandtech.echart.style.ItemStyle : itemStyle
  com.grandtech.echart.series.other.Level o-- com.grandtech.echart.style.ItemStyle : label
  com.grandtech.echart.series.other.RippleEffect .up.|> java.io.Serializable
  com.grandtech.echart.series.other.RippleEffect o-- com.grandtech.echart.code.BrushType : brushType
  com.grandtech.echart.series.other.RootLocation .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
