@startuml

title __BASE's Class Diagram__\n

  namespace com.gykj.smartdialogmoudle {
    namespace base {
      abstract class com.gykj.smartdialogmoudle.base.BaseAnimatorSet {
          # animatorSet : AnimatorSet
          # duration : long
          - delay : long
          - interpolator : Interpolator
          + delay()
          + duration()
          + interpolator()
          + listener()
          + playOn()
          {static} + reset()
          {abstract} + setAnimation()
          # start()
      }
    }
  }
  

  namespace com.gykj.smartdialogmoudle {
    namespace base {
      interface com.gykj.smartdialogmoudle.base.BaseAnimatorSet.AnimatorListener {
          {abstract} + onAnimationCancel()
          {abstract} + onAnimationEnd()
          {abstract} + onAnimationRepeat()
          {abstract} + onAnimationStart()
      }
    }
  }
  

  namespace com.gykj.smartdialogmoudle {
    namespace base {
      abstract class com.gykj.smartdialogmoudle.base.BaseDialog {
          # ll_control_height : LinearLayout
          - cancel : boolean
          - context : Context
          - dm : DisplayMetrics
          - heightScale : float
          - isDismissAnim : boolean
          - isShowAnim : boolean
          - ll_top : LinearLayout
          - maxHeight : float
          - widthScale : float
          + BaseDialog()
          + BaseDialog()
          + dismiss()
          + dismissAnim()
          + dispatchTouchEvent()
          + heightScale()
          + onAttachedToWindow()
          + onBackPressed()
          {abstract} + onCreateView()
          + setCanceledOnTouchOutside()
          {abstract} + setUiBeforShow()
          + show()
          + showAnim()
          + superDismiss()
          + widthScale()
          # onCreate()
      }
    }
  }
  

  namespace com.gykj.smartdialogmoudle {
    namespace base {
      enum DialogAnimType {
        ALPHA
        NONE
        ROTATE_H
        ROTATE_V
        SCALE_H
        SCALE_V
        TRANSLATE_B_T
        TRANSLATE_L_R
        TRANSLATE_R_L
        TRANSLATE_T_B
        name
        value
      }
    }
  }
  

  com.gykj.smartdialogmoudle.base.BaseAnimatorSet o-- com.gykj.smartdialogmoudle.base.BaseAnimatorSet.AnimatorListener : listener
  com.gykj.smartdialogmoudle.base.BaseAnimatorSet +-down- com.gykj.smartdialogmoudle.base.BaseAnimatorSet.AnimatorListener
  com.gykj.smartdialogmoudle.base.BaseDialog -up-|> android.app.Dialog
  com.gykj.smartdialogmoudle.base.BaseDialog o-- com.gykj.smartdialogmoudle.base.BaseAnimatorSet : dismissAnim
  com.gykj.smartdialogmoudle.base.BaseDialog o-- com.gykj.smartdialogmoudle.base.BaseAnimatorSet : showAnim


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
