@startuml

title __BEAN's Class Diagram__\n

  namespace com.gykj.autoupdate {
    namespace bean {
      class com.gykj.autoupdate.bean.AliOssBasePath {
          - accessKeyId : String
          - bucket : String
          - endpoint : String
          + getAccessKeyId()
          + getBucket()
          + getEndpoint()
          + setAccessKeyId()
          + setBucket()
          + setEndpoint()
      }
    }
  }
  

  namespace com.gykj.autoupdate {
    namespace bean {
      class com.gykj.autoupdate.bean.AppPath {
          - desc : String
          - name : String
          - path : String
          + getDesc()
          + getName()
          + getPath()
          + setDesc()
          + setName()
          + setPath()
      }
    }
  }
  

  namespace com.gykj.autoupdate {
    namespace bean {
      class com.gykj.autoupdate.bean.BaseResult {
          - areacode : String
          - code : int
          - datas : List<T>
          - dept : Map
          - deptroot : Map
          - hotfixVersion : int
          - message : String
          - msg : String
          - token : String
          - user : Map
          + addData()
          {static} + convert()
          + getAreacode()
          + getCode()
          + getData()
          + getDatas()
          + getDept()
          + getDeptroot()
          + getHotfixVersion()
          + getMessage()
          + getMsg()
          + getToken()
          + getUser()
          + isFail()
          + isSuccess()
          + setAreacode()
          + setCode()
          + setData()
          + setDept()
          + setDeptroot()
          + setHotfixVersion()
          + setMessage()
          + setMsg()
          + setToken()
          + setUser()
      }
    }
  }
  

  namespace com.gykj.autoupdate {
    namespace bean {
      class com.gykj.autoupdate.bean.FilePoint {
          - fileName : String
          - filePath : String
          - url : String
          + FilePoint()
          + FilePoint()
          + FilePoint()
          + getFileName()
          + getFilePath()
          + getUrl()
          + setFileName()
          + setFilePath()
          + setUrl()
      }
    }
  }
  

  namespace com.gykj.autoupdate {
    namespace bean {
      class com.gykj.autoupdate.bean.SysVersion {
          - applicationKey : String
          - applicationName : String
          - gmtCreate : String
          - gmtFinish : String
          - gmtModify : String
          - hotfixVersion : int
          - updateType : Long
          - versionCode : Long
          - versionId : String
          - versionName : String
          - versionPath : String
          - versionState : Long
          - versionTip : String
          + getApplicationKey()
          + getApplicationName()
          + getGmtCreate()
          + getGmtFinish()
          + getGmtModify()
          + getHotfixVersion()
          + getUpdateType()
          + getVersionCode()
          + getVersionId()
          + getVersionName()
          + getVersionPath()
          + getVersionState()
          + getVersionTip()
          + setApplicationKey()
          + setApplicationName()
          + setGmtCreate()
          + setGmtFinish()
          + setGmtModify()
          + setHotfixVersion()
          + setUpdateType()
          + setVersionCode()
          + setVersionId()
          + setVersionName()
          + setVersionPath()
          + setVersionState()
          + setVersionTip()
          + toString()
      }
    }
  }
  

  com.gykj.autoupdate.bean.AliOssBasePath .up.|> java.io.Serializable
  com.gykj.autoupdate.bean.AppPath .up.|> java.io.Serializable
  com.gykj.autoupdate.bean.BaseResult .up.|> java.io.Serializable
  com.gykj.autoupdate.bean.BaseResult o-- T : data
  com.gykj.autoupdate.bean.SysVersion .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
