@startuml

title __COMMON's Class Diagram__\n

  namespace com.gykj.arcgistool {
    namespace common {
      enum DrawType {
        LINE
        POINT
        POLYGON
        TEXT
      }
    }
  }
  

  namespace com.gykj.arcgistool {
    namespace common {
      enum GraphType {
        BOX
        CIRCLE
        ELLIPSE
        LINE
        POINT
        POLYGON
        RHOMBUS
      }
    }
  }
  

  namespace com.gykj.arcgistool {
    namespace common {
      interface com.gykj.arcgistool.common.IToolBar {
      }
    }
  }
  

  namespace com.gykj.arcgistool {
    namespace common {
      class com.gykj.arcgistool.common.MapViewOnTouchListener {
          + onDoubleTap()
          + onDoubleTapEvent()
          + onDoubleTouchDrag()
          + onDown()
          + onFling()
          + onLongPress()
          + onMultiPointerTap()
          + onRotate()
          + onScale()
          + onScaleBegin()
          + onScaleEnd()
          + onScroll()
          + onShowPress()
          + onSingleTapConfirmed()
          + onSingleTapUp()
          + onTouch()
          + onUp()
      }
    }
  }
  

  namespace com.gykj.arcgistool {
    namespace common {
      enum Measure {
        A2
        HM2
        KIM
        KM
        KM2
        M
        M2
      }
    }
  }
  

  namespace com.gykj.arcgistool {
    namespace common {
      class com.gykj.arcgistool.common.Variable {
      }
    }
  }
  

  com.gykj.arcgistool.common.MapViewOnTouchListener .up.|> com.gykj.arcgistool.listener.IOnTouchListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
