@startuml

title __NET's Class Diagram__\n

  namespace com.gykj.autoupdate {
    namespace net {
      interface com.gykj.autoupdate.net.DownloadListner {
          {abstract} + onCancel()
          {abstract} + onFinished()
          {abstract} + onPause()
          {abstract} + onProgress()
      }
    }
  }
  

  namespace com.gykj.autoupdate {
    namespace net {
      class com.gykj.autoupdate.net.DownloadManager {
          {static} - TAG : String
          - isMultithread : boolean
          - mDownloadTasks : Map<String, DownloadTask>
          {static} - mInstance : DownloadManager
          + DownloadManager()
          + add()
          + add()
          + add()
          + cancel()
          + download()
          {static} + getInstance()
          + isDownloading()
          + isMultithread()
          + pause()
          + setMultithread()
      }
    }
  }
  

  namespace com.gykj.autoupdate {
    namespace net {
      class com.gykj.autoupdate.net.DownloadTask {
          {static} - MSG_CANCEL : int
          {static} - MSG_FINISH : int
          {static} - MSG_PAUSE : int
          {static} - MSG_PROGRESS : int
          {static} - MSG_SINGLE : int
          {static} - MSG_SINGLE_FINISH : int
          {static} - TAG : String
          - THREAD_COUNT : int
          - cancel : boolean
          - childCanleCount : AtomicInteger
          - childFinshCount : AtomicInteger
          - childPauseCount : AtomicInteger
          - isDownloading : boolean
          - isSuportMultithread : boolean
          - mCacheFiles : File[]
          - mFileLength : long
          - mProgress : long[]
          - mTmpFile : File
          - pause : boolean
          - pro : int
          + cancel()
          + handleMessage()
          + isDownloading()
          + pause()
          + setSuportMultithread()
          + start()
          ~ DownloadTask()
          - cleanFile()
          - close()
          - confirmStatus()
          - download()
          - resetStutus()
      }
    }
  }
  

  namespace com.gykj.autoupdate {
    namespace net {
      class com.gykj.autoupdate.net.HttpUtil {
          {static} - CONNECT_TIMEOUT : long
          {static} - READ_TIMEOUT : long
          {static} - WRITE_TIMEOUT : long
          {static} - mInstance : HttpUtil
          - mOkHttpClient : OkHttpClient
          + HttpUtil()
          + downloadFileByRange()
          + getContentLength()
          {static} + getInstance()
          + postBody()
          - doAsync()
          - doSync()
      }
    }
  }
  

  com.gykj.autoupdate.net.DownloadTask -up-|> android.os.Handler
  com.gykj.autoupdate.net.DownloadTask o-- com.gykj.autoupdate.net.HttpUtil : mHttpUtil
  com.gykj.autoupdate.net.DownloadTask o-- com.gykj.autoupdate.net.DownloadListner : mListner
  com.gykj.autoupdate.net.DownloadTask o-- com.gykj.autoupdate.bean.FilePoint : mPoint


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
