@startuml

title __FILE's Class Diagram__\n

  namespace com.gykj.grandphotos {
    namespace utils.file {
      class com.gykj.grandphotos.utils.file.FileUtils {
          {static} + DOCUMENTS_DIR : String
          {static} + HIDDEN_PREFIX : String
          {static} ~ TAG : String
          {static} - DEBUG : boolean
          {static} + createGetContentIntent()
          {static} + createTempImageFile()
          {static} + generateFileName()
          {static} + getDataColumn()
          {static} + getDocumentCacheDir()
          {static} + getDownloadsDir()
          {static} + getExtension()
          {static} + getFile()
          {static} + getFileName()
          {static} + getMimeType()
          {static} + getMimeType()
          {static} + getMimeType()
          {static} + getName()
          {static} + getPath()
          {static} + getPathWithoutFilename()
          {static} + getReadableFileSize()
          {static} + getUri()
          {static} + getViewIntent()
          {static} + isDownloadsDocument()
          {static} + isExternalStorageDocument()
          {static} + isGooglePhotosUri()
          {static} + isLocal()
          {static} + isLocalStorageDocument()
          {static} + isMediaDocument()
          {static} + isMediaUri()
          {static} + readBytesFromFile()
          - FileUtils()
          {static} - getLocalPath()
          {static} - logDir()
          {static} - saveFileFromUri()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
