@startuml

title __MANAGER's Class Diagram__\n

  namespace com.grandtech.mapframe.ui {
    namespace manager {
      interface com.grandtech.mapframe.ui.manager.IToolManger {
          {abstract} + activateTool()
          {abstract} + addToolBarView()
          {abstract} + addView()
          {abstract} + deactivateTool()
          {abstract} + getToolGroupViewByName()
          {abstract} + getToolViewByName()
          {abstract} + getToolViews()
          {abstract} + init()
          {abstract} + removeView()
          {abstract} + toolBarNavigate()
      }
    }
  }
  

  namespace com.grandtech.mapframe.ui {
    namespace manager {
      class com.grandtech.mapframe.ui.manager.ToolManager {
          + activateTool()
          + addToolBarView()
          + addView()
          + deactivateTool()
          + getToolGroupDraw()
          + getToolGroupViewByName()
          + getToolViewByName()
          + getToolViews()
          + init()
          {static} + newInstance()
          + removeView()
          + setOnToolClickListener()
          + toolBarNavigate()
          + toolViewClick()
          + toolViewLongClick()
          - activate()
          - exclusion()
          - getToolGroupViewByName()
          - initEvent()
      }
    }
  }
  

  namespace com.grandtech.mapframe.ui {
    namespace manager {
      interface com.grandtech.mapframe.ui.manager.ToolManager.OnToolViewActivateListener {
          {abstract} + activate()
          {abstract} + deactivate()
      }
    }
  }
  

  namespace com.grandtech.mapframe.ui {
    namespace manager {
      enum ToolNameEnum {
        ADD
        CUT
        DIG
        DRAW
        IMAGESWITCHING
        IN
        ISEARCH
        LOC
        MERGE
        NAV
        OUT
        SELECT
        SKETCH_ADD
        SKETCH_CANCEL
        SKETCH_CANDO
        SKETCH_SAVE
        SKETCH_UNDO
        name
      }
    }
  }
  

  namespace com.grandtech.mapframe.ui {
    namespace manager {
      enum WidgetGravityEnum {
        BOTTOM
        BOTTOM_CENTER
        CENTER
        LEFT
        LEFT_BOTTOM
        LEFT_CENTER
        LEFT_TOP
        RIGHT
        RIGHT_BOTTOM
        RIGHT_CENTER
        RIGHT_TOP
        TOP
        TOP_CENTER
        name
        value
      }
    }
  }
  

  com.grandtech.mapframe.ui.manager.ToolManager .up.|> com.grandtech.mapframe.ui.manager.IToolManger
  com.grandtech.mapframe.ui.manager.ToolManager .up.|> com.grandtech.mapframe.ui.view.IToolView.IClick
  com.grandtech.mapframe.ui.manager.ToolManager .up.|> com.grandtech.mapframe.ui.view.IToolView.ILongClick
  com.grandtech.mapframe.ui.manager.ToolManager o-- com.grandtech.mapframe.ui.view.IToolView : mActivateTool
  com.grandtech.mapframe.ui.manager.ToolManager o-- com.grandtech.mapframe.ui.manager.ToolManager.OnToolViewActivateListener : mOnToolClickListener
  com.grandtech.mapframe.ui.manager.ToolManager o-- com.grandtech.mapframe.ui.view.DragLayout : mToolDragLayout
  com.grandtech.mapframe.ui.manager.ToolManager o-- com.grandtech.mapframe.ui.view.ToolGroupLayout : mToolGroupDraw
  com.grandtech.mapframe.ui.manager.ToolManager +-down- com.grandtech.mapframe.ui.manager.ToolManager.OnToolViewActivateListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
