@startuml

title __OSS's Class Diagram__\n

  namespace com.gykj.autoupdate {
    namespace oss {
      class com.gykj.autoupdate.oss.BasePathMsg {
          - accessKeyId : String
          - bucket : String
          - endpoint : String
          + BasePathMsg()
          + BasePathMsg()
          + equals()
          + getAccessKeyId()
          + getBucket()
          + getEndpoint()
          + hashCode()
          + setAccessKeyId()
          + setBucket()
          + setEndpoint()
          + toString()
          - equalsStr()
      }
    }
  }
  

  namespace com.gykj.autoupdate {
    namespace oss {
      interface com.gykj.autoupdate.oss.DownloadListener {
          {abstract} + onFaile()
          {abstract} + onProgressChange()
          {abstract} + onUpSuccess()
      }
    }
  }
  

  namespace com.gykj.autoupdate {
    namespace oss {
      class com.gykj.autoupdate.oss.FileInformation {
          - name : String
          - path : String
          + FileInformation()
          + FileInformation()
          + getName()
          + getPath()
          + setName()
          + setPath()
      }
    }
  }
  

  namespace com.gykj.autoupdate {
    namespace oss {
      class com.gykj.autoupdate.oss.MyPutObjectRequest {
      }
    }
  }
  

  namespace com.gykj.autoupdate {
    namespace oss {
      class com.gykj.autoupdate.oss.OSSFile {
          - endPoint : String
          - fileName : String
          - key : String
          - ossAccessKeyId : String
          - ossBucketName : String
          + getEndPoint()
          + getFileName()
          + getKey()
          + getOssAccessKeyId()
          + getOssBucketName()
          + setEndPoint()
          + setFileName()
          + setKey()
          + setOssAccessKeyId()
          + setOssBucketName()
      }
    }
  }
  

  namespace com.gykj.autoupdate {
    namespace oss {
      class com.gykj.autoupdate.oss.UpCenter {
          - accessKeyId : String
          - bucketName : String
          - endPoint : String
          - oss : OSS
          - resultInfo : List<OSSFile>
          - sign_server_url : String
          + UpCenter()
          + close()
          + deleteFile()
          + downloadObjectToFile()
          + generateTempUrl()
          + getDownloadUrl()
          + isExist()
          + upFile()
          + upFile()
          + upFiles()
          - generatePath()
          - initOSS()
      }
    }
  }
  

  namespace com.gykj.autoupdate {
    namespace oss {
      interface com.gykj.autoupdate.oss.UpFileListener {
          {abstract} + onFaile()
          {abstract} + onProgressChange()
          {abstract} + onUpSuccess()
      }
    }
  }
  

  com.gykj.autoupdate.oss.BasePathMsg .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
