@startuml

title __EVENT's Class Diagram__\n

  namespace com.gradtech.mapframev10 {
    namespace core.event {
      interface com.gradtech.mapframev10.core.event.IMapEvent {
          + onCameraIdle()
          + onCameraMove()
          + onCameraMoveStarted()
          + onFling()
          + onFpsChanged()
          + onMapClick()
          + onMapLongClick()
          + onScroll()
          + onTouchCancel()
          + onTouchMoving()
          + onTouchStart()
      }
    }
  }
  

  namespace com.gradtech.mapframev10 {
    namespace core.event {
      class com.gradtech.mapframev10.core.event.MapEventDispatch {
          - mIMapEvent : List<IMapEvent>
          + MapEventDispatch()
          + addIMapEvent()
          + onFling()
          + onFpsChanged()
          + onMapClick()
          + onMapLongClick()
          + onMove()
          + onMoveBegin()
          + onMoveEnd()
          + onScale()
          + onScaleBegin()
          + onScaleEnd()
          + onTouchCancel()
          + onTouchMoving()
          + onTouchStart()
          + removeIMapEvent()
      }
    }
  }
  

  namespace com.gradtech.mapframev10 {
    namespace core.event {
      abstract class com.gradtech.mapframev10.core.event.MapExtentEvent {
          - mOnTouchListenerList : List<OnTouchListener>
          + MapExtentEvent()
          + addOnTouchListener()
          + onTouch()
          {abstract} + onTouchCancel()
          {abstract} + onTouchMoving()
          {abstract} + onTouchStart()
          + removeOnTouchListener()
      }
    }
  }
  

  com.gradtech.mapframev10.core.event.MapEventDispatch .up.|> com.mapbox.maps.plugin.gestures.OnFlingListener
  com.gradtech.mapframev10.core.event.MapEventDispatch .up.|> com.mapbox.maps.plugin.gestures.OnMapClickListener
  com.gradtech.mapframev10.core.event.MapEventDispatch .up.|> com.mapbox.maps.plugin.gestures.OnMapLongClickListener
  com.gradtech.mapframev10.core.event.MapEventDispatch .up.|> com.mapbox.maps.plugin.gestures.OnMoveListener
  com.gradtech.mapframev10.core.event.MapEventDispatch .up.|> com.mapbox.maps.plugin.gestures.OnScaleListener
  com.gradtech.mapframev10.core.event.MapEventDispatch .up.|> com.mapbox.maps.renderer.OnFpsChangedListener
  com.gradtech.mapframev10.core.event.MapEventDispatch -up-|> com.gradtech.mapframev10.core.event.MapExtentEvent
  com.gradtech.mapframev10.core.event.MapExtentEvent .up.|> android.view.View.OnTouchListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
