@startuml

title __POPUP's Class Diagram__\n

  namespace com.gykj.selectlinearlayout {
    namespace popup {
      abstract class com.gykj.selectlinearlayout.popup.BasicPopup {
          {static} + MATCH_PARENT : int
          {static} + WRAP_CONTENT : int
          # activity : Activity
          # screenHeightPixels : int
          # screenWidthPixels : int
          - contentLayout : FrameLayout
          - dialog : Dialog
          - isPrepared : boolean
          + BasicPopup()
          + dismiss()
          + getContentView()
          + getContext()
          + getRootView()
          + getScreenHeightPixels()
          + getScreenWidthPixels()
          + getWindow()
          + isShowing()
          + onBackPress()
          + onDismiss()
          + onKey()
          + setAnimationStyle()
          + setCancelable()
          + setCanceledOnTouchOutside()
          + setContentView()
          + setFillScreen()
          + setFitsSystemWindows()
          + setGravity()
          + setHalfScreen()
          + setHeight()
          + setOnDismissListener()
          + setOnKeyListener()
          + setPrepared()
          + setSize()
          + setWidth()
          + show()
          # dismissImmediately()
          {abstract} # makeContentView()
          # setContentViewAfter()
          # setContentViewBefore()
          # showAfter()
          - initDialog()
      }
    }
  }
  

  namespace com.gykj.selectlinearlayout {
    namespace popup {
      abstract class com.gykj.selectlinearlayout.popup.ConfirmPopup {
          # backgroundColor : int
          # cancelButton : TextView
          # cancelText : CharSequence
          # cancelTextColor : int
          # cancelTextSize : int
          # cancelVisible : boolean
          # centerView : View
          # contentLeftAndRightPadding : int
          # contentTopAndBottomPadding : int
          # footerView : View
          # headerView : View
          # pressedTextColor : int
          # submitButton : TextView
          # submitText : CharSequence
          # submitTextColor : int
          # submitTextSize : int
          # titleText : CharSequence
          # titleTextColor : int
          # titleTextSize : int
          # titleView : View
          # topBackgroundColor : int
          # topHeight : int
          # topLineColor : int
          # topLineHeightPixels : int
          # topLineVisible : boolean
          # topPadding : int
          + ConfirmPopup()
          + getCancelButton()
          + getSubmitButton()
          + getTitleView()
          + setBackgroundColor()
          + setCancelText()
          + setCancelText()
          + setCancelTextColor()
          + setCancelTextSize()
          + setCancelVisible()
          + setContentPadding()
          + setFooterView()
          + setHeaderView()
          + setPressedTextColor()
          + setSubmitText()
          + setSubmitText()
          + setSubmitTextColor()
          + setSubmitTextSize()
          + setTitleText()
          + setTitleText()
          + setTitleTextColor()
          + setTitleTextSize()
          + setTitleView()
          + setTopBackgroundColor()
          + setTopHeight()
          + setTopLineColor()
          + setTopLineHeight()
          + setTopLineVisible()
          + setTopPadding()
          {abstract} # makeCenterView()
          # makeContentView()
          # makeFooterView()
          # makeHeaderView()
          # onCancel()
          # onSubmit()
      }
    }
  }
  

  com.gykj.selectlinearlayout.popup.BasicPopup .up.|> android.content.DialogInterface.OnDismissListener
  com.gykj.selectlinearlayout.popup.BasicPopup .up.|> android.content.DialogInterface.OnKeyListener
  com.gykj.selectlinearlayout.popup.ConfirmPopup -up-|> com.gykj.selectlinearlayout.popup.BasicPopup


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
