@startuml

title __LOCATIONSERVICE's Class Diagram__\n

  namespace com.gykj.locationservice {
    class com.gykj.locationservice.Gps {
        - wgLat : double
        - wgLon : double
        + Gps()
        + getWgLat()
        + getWgLon()
        + setWgLat()
        + setWgLon()
    }
  }
  

  namespace com.gykj.locationservice {
    class com.gykj.locationservice.LocService {
        ~ handler : Handler
        - cLocation : Location
        - interval : int
        - locationManager : LocationManager
        - minDistance : int
        - minTime : int
        + getServiceLocation()
        + onBind()
        + onDestroy()
        + onGpsStatusChanged()
        + onLocationChanged()
        + onProviderDisabled()
        + onProviderEnabled()
        + onStatusChanged()
        # doCommandInBackGrounding()
        # doCommandInBackGroundingInitialize()
        # doInBackGrounding()
        # doInBackGroundingInitialize()
        - getLocation()
        - listenLoc()
        - updateGpsStatus()
    }
  }
  

  namespace com.gykj.locationservice {
    class com.gykj.locationservice.LocationClient {
        - conn : ServiceConnection
        - isBind : boolean
        - isBinderService : boolean
        - isPermanent : boolean
        - locIntentSer : Intent
        {static} - locationClient : LocationClient
        {static} + getInstance()
        + startLoc()
        + stopLoc()
    }
  }
  

  namespace com.gykj.locationservice {
    class com.gykj.locationservice.PositionUtil {
        {static} + a : double
        {static} - ee : double
        {static} - pi : double
        {static} + bd09_To_Gcj02()
        {static} + bd09_To_Gps84()
        {static} + gcj02_To_Bd09()
        {static} + gcj02_To_Gps84()
        {static} + gps84_To_Dd09()
        {static} + gps84_To_Gcj02()
        {static} + outOfChina()
        {static} + transform()
        {static} + transformLat()
        {static} + transformLon()
    }
  }
  

  namespace com.gykj.locationservice {
    class com.gykj.locationservice.ServiceLocation {
        - latitude : Double
        - location : Location
        - longitude : Double
        - satelliteCount : Integer
        - validSatelliteCount : Integer
        + getLatitude()
        + getLocation()
        + getLongitude()
        + getSatelliteCount()
        + getValidSatelliteCount()
        + geteSignal()
        + setLatitude()
        + setLocation()
        + setLongitude()
        + setSatelliteCount()
        + setValidSatelliteCount()
        + seteSignal()
    }
  }
  

  namespace com.gykj.locationservice {
    enum ESignal {
      HIGH
      LOW
      MIDDLE
    }
  }
  

  com.gykj.locationservice.LocService .up.|> android.location.GpsStatus.Listener
  com.gykj.locationservice.LocService .up.|> android.location.LocationListener
  com.gykj.locationservice.LocService -up-|> com.gykj.locationservice.baseservices.v2.BaseService
  com.gykj.locationservice.LocService o-- com.gykj.locationservice.ServiceLocation.ESignal : eSignal
  com.gykj.locationservice.LocService o-- com.gykj.locationservice.ServiceLocation : serviceLocation
  com.gykj.locationservice.ServiceLocation o-- com.gykj.locationservice.ServiceLocation.ESignal : eSignal
  com.gykj.locationservice.ServiceLocation +-down- com.gykj.locationservice.ServiceLocation.ESignal


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
