@startuml

title __EDITOR's Class Diagram__\n

  namespace com.grandtech.mapframe.core {
    namespace editor {
      class com.grandtech.mapframe.core.editor.BaseEditor {
          + BaseEditor()
          + addFeatures()
          + delFeatures()
          + digFeatures()
          + drawFeature()
          + editFeature()
          + getGraphicContainer()
          + splitFeatures()
          + unionFeatures()
          - assembleCopy()
          - assembleDig()
          - assembleEdit()
          - assembleNewDraw()
          - assembleSplit()
          - assembleUnion()
          - featureValid()
          - featuresValid()
          - selectSetClone()
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace editor {
      interface com.grandtech.mapframe.core.editor.IEditor {
          {abstract} + addFeatures()
          {abstract} + delFeatures()
          {abstract} + digFeatures()
          {abstract} + drawFeature()
          {abstract} + editFeature()
          {abstract} + splitFeatures()
          {abstract} + unionFeatures()
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace editor {
      interface com.grandtech.mapframe.core.editor.IGcCallBack {
          {abstract} + onError()
          {abstract} + onGcCallBack()
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace editor {
      interface com.grandtech.mapframe.core.editor.IToolInterceptor {
          {abstract} + afterHandle()
          {abstract} + doHandle()
      }
    }
  }
  

  com.grandtech.mapframe.core.editor.BaseEditor .up.|> com.grandtech.mapframe.core.editor.IEditor
  com.grandtech.mapframe.core.editor.BaseEditor o-- com.grandtech.mapframe.core.editor.gc.IGraphicContainer : mIGraphicContainer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
