@startuml

title __WIDGET's Class Diagram__\n

  namespace com.gykj.grandphotos {
    namespace ui {
      namespace widget {
        class com.gykj.grandphotos.ui.widget.PressedImageView {
            - scaleSize : float
            + PressedImageView()
            + PressedImageView()
            + PressedImageView()
            + setPressed()
            + setScaleSize()
        }
      }
    }
  }
  

  namespace com.gykj.grandphotos {
    namespace ui {
      namespace widget {
        class com.gykj.grandphotos.ui.widget.PressedTextView {
            - pressedFlag : int
            - pressedScale : float
            - set : AnimatorSet
            + PressedTextView()
            + PressedTextView()
            + PressedTextView()
            + setPressed()
            + setPressedScale()
        }
      }
    }
  }
  

  namespace com.gykj.grandphotos {
    namespace ui {
      namespace widget {
        class com.gykj.grandphotos.ui.widget.PreviewRecyclerView {
            - isLock : boolean
            + PreviewRecyclerView()
            + PreviewRecyclerView()
            + PreviewRecyclerView()
            + dispatchTouchEvent()
            + onInterceptTouchEvent()
        }
      }
    }
  }
  

  com.gykj.grandphotos.ui.widget.PressedImageView -up-|> androidx.appcompat.widget.AppCompatImageView
  com.gykj.grandphotos.ui.widget.PressedTextView -up-|> androidx.appcompat.widget.AppCompatTextView
  com.gykj.grandphotos.ui.widget.PreviewRecyclerView -up-|> androidx.recyclerview.widget.RecyclerView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
