@startuml

title __EVENT's Class Diagram__\n

  namespace com.grandtech.echart {
    namespace series {
      namespace event {
        class com.grandtech.echart.series.event.Detail {
            - img : String
            - link : String
            {static} - serialVersionUID : long
            - text : String
            + Detail()
            + Detail()
            + Detail()
            + getImg()
            + getLink()
            + getText()
            + img()
            + img()
            + link()
            + link()
            + setImg()
            + setLink()
            + setText()
            + text()
            + text()
        }
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace series {
      namespace event {
        class com.grandtech.echart.series.event.Event {
            - evolution : List<Evolution>
            - name : String
            {static} - serialVersionUID : long
            - weight : Integer
            + Event()
            + Event()
            + Event()
            + evolution()
            + evolution()
            + evolution()
            + getEvolution()
            + getName()
            + getWeight()
            + name()
            + name()
            + setEvolution()
            + setName()
            + setWeight()
            + weight()
            + weight()
        }
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace series {
      namespace event {
        class com.grandtech.echart.series.event.Evolution {
            {static} - FORMAT : SimpleDateFormat
            {static} - serialVersionUID : long
            - time : String
            - value : Integer
            + Evolution()
            + Evolution()
            + detail()
            + detail()
            + detail()
            + detail()
            + getDetail()
            + getTime()
            + getValue()
            + setDetail()
            + setTime()
            + setValue()
            + time()
            + time()
            + time()
            + value()
            + value()
        }
      }
    }
  }
  

  com.grandtech.echart.series.event.Detail .up.|> java.io.Serializable
  com.grandtech.echart.series.event.Event .up.|> java.io.Serializable
  com.grandtech.echart.series.event.Evolution .up.|> java.io.Serializable
  com.grandtech.echart.series.event.Evolution o-- com.grandtech.echart.series.event.Detail : detail


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
