@startuml

title __ATTENTION's Class Diagram__\n

  namespace com.gykj.smartdialogmoudle {
    namespace anims {
      namespace Attention {
        class com.gykj.smartdialogmoudle.anims.Attention.Flash {
            + Flash()
            + setAnimation()
        }
      }
    }
  }
  

  namespace com.gykj.smartdialogmoudle {
    namespace anims {
      namespace Attention {
        class com.gykj.smartdialogmoudle.anims.Attention.RubberBand {
            + RubberBand()
            + setAnimation()
        }
      }
    }
  }
  

  namespace com.gykj.smartdialogmoudle {
    namespace anims {
      namespace Attention {
        class com.gykj.smartdialogmoudle.anims.Attention.ShakeHorizontal {
            + ShakeHorizontal()
            + setAnimation()
        }
      }
    }
  }
  

  namespace com.gykj.smartdialogmoudle {
    namespace anims {
      namespace Attention {
        class com.gykj.smartdialogmoudle.anims.Attention.ShakeVertical {
            + ShakeVertical()
            + setAnimation()
        }
      }
    }
  }
  

  namespace com.gykj.smartdialogmoudle {
    namespace anims {
      namespace Attention {
        class com.gykj.smartdialogmoudle.anims.Attention.Swing {
            + Swing()
            + setAnimation()
        }
      }
    }
  }
  

  namespace com.gykj.smartdialogmoudle {
    namespace anims {
      namespace Attention {
        class com.gykj.smartdialogmoudle.anims.Attention.Tada {
            + Tada()
            + setAnimation()
        }
      }
    }
  }
  

  com.gykj.smartdialogmoudle.anims.Attention.Flash -up-|> com.gykj.smartdialogmoudle.base.BaseAnimatorSet
  com.gykj.smartdialogmoudle.anims.Attention.RubberBand -up-|> com.gykj.smartdialogmoudle.base.BaseAnimatorSet
  com.gykj.smartdialogmoudle.anims.Attention.ShakeHorizontal -up-|> com.gykj.smartdialogmoudle.base.BaseAnimatorSet
  com.gykj.smartdialogmoudle.anims.Attention.ShakeVertical -up-|> com.gykj.smartdialogmoudle.base.BaseAnimatorSet
  com.gykj.smartdialogmoudle.anims.Attention.Swing -up-|> com.gykj.smartdialogmoudle.base.BaseAnimatorSet
  com.gykj.smartdialogmoudle.anims.Attention.Tada -up-|> com.gykj.smartdialogmoudle.base.BaseAnimatorSet


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
