@startuml

title __JSON's Class Diagram__\n

  namespace com.grandtech.echart {
    namespace json {
      class com.grandtech.echart.json.AxisDeserializer {
          + deserialize()
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace json {
      class com.grandtech.echart.json.GsonOption {
          + exportToHtml()
          + exportToHtml()
          + toPrettyString()
          + toString()
          + view()
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace json {
      class com.grandtech.echart.json.GsonUtil {
          {static} + format()
          {static} + fromJSON()
          {static} + fromJSON()
          {static} + prettyFormat()
          {static} + print()
          {static} + printPretty()
          {static} + replaceFunctionQuote()
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace json {
      class com.grandtech.echart.json.OptionUtil {
          {static} + browse()
          {static} + browse()
          {static} + exportToHtml()
          {static} + exportToHtml()
          {static} + exportToHtml()
          - OptionUtil()
          {static} - getFolderPath()
          {static} - readLines()
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace json {
      class com.grandtech.echart.json.SeriesDeserializer {
          + deserialize()
      }
    }
  }
  

  com.grandtech.echart.json.AxisDeserializer .up.|> com.google.gson.JsonDeserializer
  com.grandtech.echart.json.GsonOption -up-|> com.grandtech.echart.Option
  com.grandtech.echart.json.SeriesDeserializer .up.|> com.google.gson.JsonDeserializer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
