@startuml

title __SYSTEM's Class Diagram__\n

  namespace com.gykj.grandphotos {
    namespace utils.system {
      class com.gykj.grandphotos.utils.system.MeiZuStatusUtils {
          {static} - SYSTEM_UI_FLAG_LIGHT_STATUS_BAR : int
          {static} - mSetStatusBarColorIcon : Method
          {static} - mSetStatusBarDarkIcon : Method
          {static} - mStatusBarColorFiled : Field
          {static} + isBlackColor()
          {static} + setStatusBarDarkIcon()
          {static} + setStatusBarDarkIcon()
          {static} + setStatusBarDarkIcon()
          {static} + setStatusBarDarkIcon()
          {static} + toGrey()
          {static} - changeMeizuFlag()
          {static} - setStatusBarColor()
          {static} - setStatusBarDarkIcon()
          {static} - setStatusBarDarkIcon()
      }
    }
  }
  

  namespace com.gykj.grandphotos {
    namespace utils.system {
      class com.gykj.grandphotos.utils.system.SystemUtils {
          - hasNavigation : Boolean
          {static} - instance : SystemUtils
          {static} + getInstance()
          + getStatusBarHeight()
          + hasNavigationBar()
          + setStatusDark()
          + systemUiHide()
          + systemUiInit()
          + systemUiShow()
          - SystemUtils()
          - getSystemProperty()
          - hideStatusBar()
          - isAndroidMOrAbove()
          - isFlymeV4OrAbove()
          - isMIUIV6OrAbove()
          - setStatusTextBlackAndroid()
          - setStatusTextBlackMi()
          - showStatusBar()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
