@startuml

title __BEAN's Class Diagram__\n

  namespace com.gykj.cameramodule {
    namespace bean {
      class com.gykj.cameramodule.bean.ImagePagerBean {
          {static} - imagePagerBean : ImagePagerBean
          - mDesc : String
          - mSmallUrl : String
          - mUrl : String
          - name : String
          + ImagePagerBean()
          + ImagePagerBean()
          + ImagePagerBean()
          + getDesc()
          + getName()
          {static} + getOneImagePagerBean()
          + getSmallUrl()
          + getUrl()
          + setDesc()
          + setName()
          + setSmallUrl()
          + setUrl()
      }
    }
  }
  

  namespace com.gykj.cameramodule {
    namespace bean {
      class com.gykj.cameramodule.bean.ImgFolderBean {
          - count : int
          - dir : String
          - firstImgPath : String
          - name : String
          + getCount()
          + getDir()
          + getFirstImagePath()
          + getName()
          + setCount()
          + setDir()
          + setFirstImagePath()
      }
    }
  }
  

  namespace com.gykj.cameramodule {
    namespace bean {
      class com.gykj.cameramodule.bean.PhotoFile {
          - desc : String
          - name : String
          - path : String
          + PhotoFile()
          + PhotoFile()
          {static} + formJson()
          + getAttrFromDesc()
          + getDesc()
          + getName()
          + getPath()
          + setDesc()
          + setName()
          + setPath()
          + toJson()
      }
    }
  }
  

  com.gykj.cameramodule.bean.ImagePagerBean .up.|> java.io.Serializable
  com.gykj.cameramodule.bean.ImagePagerBean .up.|> java.lang.Cloneable
  com.gykj.cameramodule.bean.ImgFolderBean .up.|> java.io.Serializable
  com.gykj.cameramodule.bean.PhotoFile .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
