@startuml

title __FORCE's Class Diagram__\n

  namespace com.grandtech.echart {
    namespace series {
      namespace force {
        class com.grandtech.echart.series.force.Category {
            - draggable : Boolean
            - name : String
            {static} - serialVersionUID : long
            - symbol : Object
            - symbolOffset : Object[]
            - symbolRotate : Integer
            - symbolSize : Object
            + Category()
            + Category()
            + draggable()
            + draggable()
            + getDraggable()
            + getItemStyle()
            + getLabel()
            + getName()
            + getSymbol()
            + getSymbolOffset()
            + getSymbolRotate()
            + getSymbolSize()
            + itemStyle()
            + label()
            + label()
            + name()
            + name()
            + setDraggable()
            + setItemStyle()
            + setLabel()
            + setName()
            + setSymbol()
            + setSymbolOffset()
            + setSymbolRotate()
            + setSymbolSize()
            + symbol()
            + symbol()
            + symbolOffset()
            + symbolOffset()
            + symbolOffset()
            + symbolRotate()
            + symbolRotate()
            + symbolSize()
            + symbolSize()
        }
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace series {
      namespace force {
        class com.grandtech.echart.series.force.Link {
            {static} - serialVersionUID : long
            - source : Object
            - target : Object
            - weight : Integer
            + Link()
            + Link()
            + getItemStyle()
            + getLineStyle()
            + getSource()
            + getTarget()
            + getWeight()
            + itemStyle()
            + lineStyle()
            + lineStyle()
            + setItemStyle()
            + setLineStyle()
            + setSource()
            + setTarget()
            + setWeight()
            + source()
            + source()
            + target()
            + target()
            + weight()
            + weight()
        }
      }
    }
  }
  

  namespace com.grandtech.echart {
    namespace series {
      namespace force {
        class com.grandtech.echart.series.force.Node {
            {static} - serialVersionUID : long
            + Node()
            + Node()
            + category()
            + category()
            + draggable()
            + draggable()
            + fixX()
            + fixX()
            + fixY()
            + fixY()
            + ignore()
            + ignore()
            + initial()
            + initial()
            + itemStyle()
            + label()
            + label()
            + name()
            + name()
            + symbol()
            + symbol()
            + symbolSize()
            + symbolSize()
            + value()
            + value()
        }
      }
    }
  }
  

  com.grandtech.echart.series.force.Category .up.|> java.io.Serializable
  com.grandtech.echart.series.force.Category o-- com.grandtech.echart.style.ItemStyle : itemStyle
  com.grandtech.echart.series.force.Category o-- com.grandtech.echart.style.ItemStyle : label
  com.grandtech.echart.series.force.Link .up.|> java.io.Serializable
  com.grandtech.echart.series.force.Link o-- com.grandtech.echart.style.ItemStyle : itemStyle
  com.grandtech.echart.series.force.Link o-- com.grandtech.echart.style.LineStyle : lineStyle
  com.grandtech.echart.series.force.Node .up.|> java.io.Serializable
  com.grandtech.echart.series.force.Node -up-|> java.util.HashMap


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
