@startuml

title __SELECT's Class Diagram__\n

  namespace com.grandtech.mapframe.core {
    namespace select {
      class com.grandtech.mapframe.core.select.SelectSetting {
          ~ isMulti : boolean
          ~ isPriority : boolean
          ~ isRender : boolean
          ~ layerIds : List<String>
          - layerIdSelectMap : LinkedHashMap
          - maxSelectCount : int
          + SelectSetting()
          + SelectSetting()
          + SelectSetting()
          + SelectSetting()
          + SelectSetting()
          + SelectSetting()
          + SelectSetting()
          + getLayerIdSelectId()
          + getLayersAsList()
          + getMaxSelectCount()
          + isMulti()
          + isPriority()
          + isRender()
          + setLayerIdSelect()
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace select {
      class com.grandtech.mapframe.core.select.SelectionSet {
          - _count : int
          - _queryIdMap : Map<String, String>
          - _selectSet : Map<String, FeatureSet>
          - cacheTempLayer : Map<String, Layer>
          - changeListening : List<ISelectSetChange>
          - renderColor : int
          + SelectionSet()
          + addChangeListening()
          + clearRender()
          + clearSelectSet()
          + getSelectSet()
          + initQuery()
          + initQuery()
          + removeChangeListening()
          + render()
          + selectByPoint()
          - clearRenderStyle()
          - createExpression()
          - getSelectCount()
          - notifyBeforeSelectSetChange()
          - notifySelectSetChangeIng()
          - notifySelectSetChanged()
          - renderLayer()
          - setSelRenderStyle()
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace select {
      interface com.grandtech.mapframe.core.select.SelectionSet.ISelectSetChange {
          {abstract} + beforeSelectSetChange()
          {abstract} + selectSetChangeIng()
          {abstract} + selectSetChanged()
      }
    }
  }
  

  namespace com.grandtech.mapframe.core {
    namespace select {
      enum SelectStatus {
        addSelected
        cancelSelected
        selectedNull
      }
    }
  }
  

  com.grandtech.mapframe.core.select.SelectSetting .up.|> com.grandtech.mapframe.core.rules.Rules
  com.grandtech.mapframe.core.select.SelectionSet o-- com.grandtech.mapframe.core.maps.GMapView : _gMapView
  com.grandtech.mapframe.core.select.SelectionSet o-- com.grandtech.mapframe.core.select.SelectSetting : _selectSetting
  com.grandtech.mapframe.core.select.SelectionSet +-down- com.grandtech.mapframe.core.select.SelectionSet.ISelectSetChange
  com.grandtech.mapframe.core.select.SelectionSet +-down- com.grandtech.mapframe.core.select.SelectionSet.SelectStatus


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
